import {
  BookOpenCheck,
  BrainCircuit,
  CalendarRange,
  CircleCheckBig,
  Link2,
  MessageSquareQuote,
  NotebookText,
  PenLine,
  Search,
  Sparkles,
  Tags,
  WandSparkles,
} from 'lucide-react'
import {
  dailyJournalTemplate,
  decisionTemplate,
  insertMarkdown,
  meetingTemplate,
  monthCalendarTemplate,
  weekCalendarTemplate,
  weeklyPlanTemplate,
  type GrimoireCommandDefinition,
} from './grimoireSlashCommandActions'

export const GRIMOIRE_TEMPLATE_SLASH_COMMANDS: GrimoireCommandDefinition[] = [
  {
    key: 'grimoire_daily_journal',
    title: 'Daily Journal',
    subtext: 'Insert a dated journal template.',
    aliases: ['journal', 'daily', 'template', 'today'],
    group: 'Templates',
    icon: NotebookText,
    run: (editor, context) => insertMarkdown(editor, dailyJournalTemplate(context)),
  },
  {
    key: 'grimoire_meeting_notes',
    title: 'Meeting Notes',
    subtext: 'Agenda, decisions, and actions.',
    aliases: ['meeting', '1:1', 'standup', 'notes template'],
    group: 'Templates',
    icon: MessageSquareQuote,
    run: (editor, context) => insertMarkdown(editor, meetingTemplate(context)),
  },
  {
    key: 'grimoire_decision_note',
    title: 'Decision Note',
    subtext: 'Capture context, decision, and tradeoffs.',
    aliases: ['adr', 'decision', 'why', 'tradeoff'],
    group: 'Templates',
    icon: BookOpenCheck,
    run: (editor, context) => insertMarkdown(editor, decisionTemplate(context)),
  },
  {
    key: 'grimoire_weekly_plan',
    title: 'Weekly Plan',
    subtext: 'Create a week-range planning section.',
    aliases: ['week', 'planning', 'review', 'weekly'],
    group: 'Templates',
    icon: CalendarRange,
    run: (editor, context) => insertMarkdown(editor, weeklyPlanTemplate(context)),
  },
  {
    key: 'grimoire_week_calendar',
    title: 'Week Calendar',
    subtext: 'Insert a Mon-Sun calendar table for this week.',
    aliases: ['week calendar', 'week cal', 'calendar week', 'schedule', 'weekly calendar'],
    group: 'Templates',
    icon: CalendarRange,
    run: (editor, context) => insertMarkdown(editor, weekCalendarTemplate(context)),
  },
  {
    key: 'grimoire_month_calendar',
    title: 'Month Calendar',
    subtext: 'Insert a markdown month grid.',
    aliases: ['calendar', 'month calendar', 'month cal', 'monthly', 'schedule'],
    group: 'Templates',
    icon: CalendarRange,
    run: (editor, context) => insertMarkdown(editor, monthCalendarTemplate(context)),
  },
  {
    key: 'grimoire_project_brief',
    title: 'Project Brief',
    subtext: 'Scope, goals, milestones, and risks.',
    aliases: ['project', 'brief', 'plan', 'template'],
    group: 'Templates',
    icon: Tags,
    run: editor => insertMarkdown(editor, [
      '## Project Brief',
      '',
      'Goal',
      '',
      'Milestones',
      '- [ ] ',
      '',
      'Risks',
      '- ',
      '',
      'Links',
      '- ',
    ].join('\n')),
  },
  {
    key: 'grimoire_brain_dump',
    title: 'Brain Dump',
    subtext: 'Fast capture section for rough thoughts.',
    aliases: ['capture', 'scratch', 'inbox', 'rough note'],
    group: 'Memory',
    icon: BrainCircuit,
    run: (editor, context) => insertMarkdown(editor, [
      `## Brain Dump - ${context.today} ${context.time}`,
      '',
      '- ',
      '',
      'Clean up later',
      '- [ ] Extract actions',
      '- [ ] Add links',
    ].join('\n')),
  },
  {
    key: 'grimoire_cleanup_prompt',
    title: 'Clean Up Note',
    subtext: 'Mem-style pass: structure, headings, actions, and links.',
    aliases: ['clean up', 'cleanup', 'organize', 'polish', 'broom', 'mem'],
    group: 'Memory',
    icon: WandSparkles,
    run: editor => insertMarkdown(editor, [
      '## Clean Up',
      '',
      '> Refine this note without changing the meaning.',
      '',
      '- [ ] Fix headings and spacing',
      '- [ ] Extract action items',
      '- [ ] Add useful Spelllinks',
      '- [ ] Move source links under References',
    ].join('\n')),
  },
  {
    key: 'grimoire_summarize_note',
    title: 'Summarize Note',
    subtext: 'Create a concise summary section.',
    aliases: ['summary', 'summarize', 'recap', 'tl;dr', 'mem'],
    group: 'Memory',
    icon: Sparkles,
    run: editor => insertMarkdown(editor, [
      '## Summary',
      '',
      '- ',
      '',
      'Key points',
      '- ',
    ].join('\n')),
  },
  {
    key: 'grimoire_extract_actions',
    title: 'Extract Actions',
    subtext: 'Create a checklist for follow-ups.',
    aliases: ['actions', 'action items', 'follow ups', 'todos', 'tasks'],
    group: 'Memory',
    icon: CircleCheckBig,
    run: editor => insertMarkdown(editor, [
      '## Actions',
      '',
      '- [ ] Owner - action',
      '- [ ] ',
    ].join('\n')),
  },
  {
    key: 'grimoire_create_wikilinks',
    title: 'Create Spelllinks [[ ]]',
    subtext: 'Draft durable [[note]] links and missing targets.',
    aliases: ['[[', 'link notes', 'connect notes', 'wikilinks', 'wiki links', 'spelllinks', 'backlinks', 'entities', 'mem'],
    group: 'Memory',
    icon: Link2,
    run: editor => insertMarkdown(editor, [
      '## Spelllinks To Create',
      '',
      '- [[Note Title]] - why this should exist',
      '- [[Person or Project]] - relationship',
      '',
      'Missing targets',
      '- [[New Note]]',
    ].join('\n')),
  },
  {
    key: 'grimoire_continue_writing',
    title: 'Continue Writing',
    subtext: 'Add a focused continuation prompt.',
    aliases: ['continue', 'write more', 'draft', 'expand', 'copilot'],
    group: 'Memory',
    icon: PenLine,
    run: editor => insertMarkdown(editor, [
      '> Continue',
      '>',
      '> Extend this note in the same voice and keep the structure tight.',
    ].join('\n')),
  },
  {
    key: 'grimoire_related_context',
    title: 'Related Context',
    subtext: 'Create a place to collect linked context.',
    aliases: ['heads up', 'related', 'context', 'recall'],
    group: 'Memory',
    icon: Search,
    run: editor => insertMarkdown(editor, [
      '## Related Context',
      '',
      '- [[Note Title]]',
      '- #tag',
    ].join('\n')),
  },
  {
    key: 'grimoire_ai_prompt',
    title: 'AI Prompt Block',
    subtext: 'Capture an instruction for later AI review.',
    aliases: ['ai', 'ask', 'prompt', 'chat'],
    group: 'Memory',
    icon: Sparkles,
    run: editor => insertMarkdown(editor, [
      '> Prompt',
      '>',
      '> Summarize this note and extract action items.',
    ].join('\n')),
  },
]
