import Foundation

public extension MarkdownEditorCommandCatalog {
    static let portableCommands: [MarkdownEditorCommand] = [
        MarkdownEditorCommand(id: "grimoire_yesterday", title: "Yesterday", subtitle: "Insert yesterday's date.", aliases: ["date", "previous day", "yesterday"], group: .dates, markdownTemplate: "{yesterday}"),
        MarkdownEditorCommand(id: "grimoire_time_now", title: "Time Now", subtitle: "Insert the current local time.", aliases: ["time", "clock", "now", "timestamp"], group: .dates, markdownTemplate: "{time}"),
        MarkdownEditorCommand(id: "grimoire_daily_note_link", title: "Daily Note Link", subtitle: "Spelllink to today's daily note.", aliases: ["daily", "journal", "today link", "date link", "spelllink"], group: .dates, markdownTemplate: "[[{today}]]"),
        MarkdownEditorCommand(id: "grimoire_task_due_today", title: "Task Due Today", subtitle: "Create a checklist item due today.", aliases: ["todo today", "task today", "due today", "reminder"], group: .tasks, markdownTemplate: "- [ ] Task due {today}"),
        MarkdownEditorCommand(id: "grimoire_task_due_tomorrow", title: "Task Due Tomorrow", subtitle: "Create a checklist item due tomorrow.", aliases: ["todo tomorrow", "task tomorrow", "due tomorrow", "follow up"], group: .tasks, markdownTemplate: "- [ ] Task due {tomorrow}"),
        MarkdownEditorCommand(id: "grimoire_note_mention", title: "Note Mention", subtitle: "Start a note or person mention.", aliases: ["@", "mention", "person", "note mention", "mem mention"], group: .inline, markdownTemplate: "@"),
        MarkdownEditorCommand(id: "grimoire_link", title: "Markdown Link", subtitle: "Insert editable link text.", aliases: ["url", "href", "web link", "external link"], group: .inline, markdownTemplate: "[link text](https://example.com)"),
        MarkdownEditorCommand(id: "grimoire_bold_text", title: "Bold Text", subtitle: "Insert markdown strong text.", aliases: ["strong", "**", "emphasis"], group: .inline, markdownTemplate: "**bold text**"),
        MarkdownEditorCommand(id: "grimoire_italic_text", title: "Italic Text", subtitle: "Insert markdown emphasis text.", aliases: ["italic", "italics", "_", "em"], group: .inline, markdownTemplate: "*italic text*"),
        MarkdownEditorCommand(id: "grimoire_strike_text", title: "Strikethrough", subtitle: "Insert markdown deleted text.", aliases: ["strike", "strikethrough", "delete", "~~"], group: .inline, markdownTemplate: "~~struck text~~"),
        MarkdownEditorCommand(id: "grimoire_highlight_text", title: "Highlight Text", subtitle: "Insert Obsidian-style highlight markers.", aliases: ["highlight", "mark", "=="], group: .inline, markdownTemplate: "==highlighted text=="),
        MarkdownEditorCommand(id: "grimoire_inline_code", title: "Inline Code", subtitle: "Insert inline code text.", aliases: ["`", "code span", "monospace"], group: .inline, markdownTemplate: "`code`"),
        MarkdownEditorCommand(id: "grimoire_simple_table", title: "Simple Table", subtitle: "Insert a markdown-friendly table.", aliases: ["table", "grid", "columns", "matrix"], group: .markdown, markdownTemplate: "| Name | Owner | Status |\n| --- | --- | --- |\n|  |  |  |\n|  |  |  |"),
        MarkdownEditorCommand(id: "grimoire_comparison_table", title: "Comparison Table", subtitle: "Create a compact comparison table.", aliases: ["pros cons", "compare", "decision table", "matrix"], group: .markdown, markdownTemplate: "| Option | Pros | Cons |\n| --- | --- | --- |\n| A |  |  |\n| B |  |  |"),
        MarkdownEditorCommand(id: "grimoire_callout_note", title: "Callout Note", subtitle: "Insert a portable blockquote callout.", aliases: ["admonition", "note", "info", "blockquote"], group: .markdown, markdownTemplate: "> [!NOTE]\n> Write the note here."),
        MarkdownEditorCommand(id: "grimoire_callout_tip", title: "Callout Tip", subtitle: "Insert a tip callout.", aliases: ["tip", "hint", "lightbulb"], group: .markdown, markdownTemplate: "> [!TIP]\n> Useful detail."),
        MarkdownEditorCommand(id: "grimoire_callout_warning", title: "Callout Warning", subtitle: "Insert a warning callout.", aliases: ["warning", "caution", "alert"], group: .markdown, markdownTemplate: "> [!WARNING]\n> Risk to watch."),
        MarkdownEditorCommand(id: "grimoire_footnote", title: "Footnote", subtitle: "Insert a markdown footnote pair.", aliases: ["reference", "citation", "note ref", "[^1]"], group: .markdown, markdownTemplate: "[^1]\n\n[^1]: Reference"),
        MarkdownEditorCommand(id: "grimoire_source_block", title: "Source Block", subtitle: "Capture a source with notes.", aliases: ["citation", "reference", "link preview", "web clip"], group: .markdown, markdownTemplate: "> Source: [Title](https://example.com)\n>\n> Notes:\n> - "),
        MarkdownEditorCommand(id: "grimoire_inline_math", title: "Inline Math", subtitle: "Insert inline LaTeX math.", aliases: ["math", "latex", "formula", "$"], group: .technical, markdownTemplate: "$E=mc^2$"),
        MarkdownEditorCommand(id: "grimoire_display_math", title: "Display Math", subtitle: "Insert a display LaTeX block.", aliases: ["math block", "latex block", "equation", "$$"], group: .technical, markdownTemplate: "$$\nE=mc^2\n$$"),
    ] + mermaidPortableCommands + sadhanaPortableCommands + [
        MarkdownEditorCommand(id: "grimoire_handwritten_canvas", title: "Handwritten Canvas", subtitle: "Attach an editable handwriting canvas with a Markdown preview.", aliases: ["canvas", "handwriting", "handwritten", "ink", "pencil", "sketch"], group: .canvas, markdownTemplate: "## Handwritten Canvas - {today}\n\n![Handwritten Canvas](attachments/handwriting-{canvasStamp}.png)\n\n```grimoire-canvas\ntype: handwriting\nsource: attachments/handwriting-{canvasStamp}.grimoire-canvas.json\npreview: attachments/handwriting-{canvasStamp}.png\n```"),
        MarkdownEditorCommand(id: "grimoire_whiteboard_canvas", title: "Whiteboard Canvas", subtitle: "Attach a whiteboard canvas for diagrams and freeform thinking.", aliases: ["whiteboard", "canvas", "diagram canvas", "draw", "excalidraw"], group: .canvas, markdownTemplate: "## Whiteboard Canvas - {today}\n\n![Whiteboard Canvas](attachments/whiteboard-{canvasStamp}.png)\n\n```grimoire-canvas\ntype: whiteboard\nsource: attachments/whiteboard-{canvasStamp}.grimoire-canvas.json\npreview: attachments/whiteboard-{canvasStamp}.png\n```"),
        MarkdownEditorCommand(id: "grimoire_sketch_note", title: "Sketch Note", subtitle: "Create a note scaffold around a handwritten canvas.", aliases: ["sketch note", "hand note", "draw note", "pencil note"], group: .canvas, markdownTemplate: "## Sketch Note - {today}\n\nPrompt\n- \n\n## Handwritten Canvas - {today}\n\n![Handwritten Canvas](attachments/handwriting-{canvasStamp}.png)\n\n```grimoire-canvas\ntype: handwriting\nsource: attachments/handwriting-{canvasStamp}.grimoire-canvas.json\npreview: attachments/handwriting-{canvasStamp}.png\n```\n\nNotes\n- "),
        MarkdownEditorCommand(id: "grimoire_daily_journal", title: "Daily Journal", subtitle: "Create a daily journal scaffold.", aliases: ["daily", "journal", "today", "mem daily"], group: .templates, markdownTemplate: "# Daily Journal - {today}\n\n## Focus\n- \n\n## Notes\n- \n\n## Tasks\n- [ ] "),
        MarkdownEditorCommand(id: "grimoire_decision_note", title: "Decision Note", subtitle: "Capture options, tradeoffs, and a decision.", aliases: ["adr", "decision", "tradeoff", "option"], group: .templates, markdownTemplate: "## Decision - {today}\n\nContext\n- \n\nOptions\n1. \n2. \n\nDecision\n- \n\nConsequences\n- "),
        MarkdownEditorCommand(id: "grimoire_weekly_plan", title: "Weekly Plan", subtitle: "Plan outcomes and calendar pressure.", aliases: ["week plan", "weekly", "planning", "goals"], group: .templates, markdownTemplate: "## Weekly Plan - {weekStart} to {weekEnd}\n\nOutcomes\n- [ ] \n\nCalendar pressure\n- \n\nRisks\n- \n\nNotes\n- "),
        MarkdownEditorCommand(id: "grimoire_project_brief", title: "Project Brief", subtitle: "Set up project goal, scope, links, and next moves.", aliases: ["project", "brief", "spec", "plan"], group: .templates, markdownTemplate: "## Project Brief\n\nGoal\n- \n\nScope\n- In:\n- Out:\n\nLinks\n- [[Related Note]]\n\nNext actions\n- [ ] "),
        MarkdownEditorCommand(id: "grimoire_brain_dump", title: "Brain Dump", subtitle: "Capture messy thoughts and turn them into next actions.", aliases: ["inbox", "dump", "quick capture", "scratch"], group: .templates, markdownTemplate: "## Brain Dump - {today}\n\nRaw\n- \n\nPatterns\n- \n\nNext actions\n- [ ] "),
        MarkdownEditorCommand(id: "grimoire_summarize_note", title: "Summarize Note", subtitle: "Mark a note section for summarization.", aliases: ["summary", "summarize", "tl dr", "digest"], group: .intelligence, markdownTemplate: "> [!note] Summarize this\n> Key points, decisions, and open questions."),
        MarkdownEditorCommand(id: "grimoire_extract_actions", title: "Extract Action Items", subtitle: "Mark text for action-item extraction.", aliases: ["actions", "tasks", "todo", "extract"], group: .intelligence, markdownTemplate: "> [!todo] Extract actions\n> Convert commitments into checklist items with owners and dates."),
        MarkdownEditorCommand(id: "grimoire_create_wikilinks", title: "Create Spelllinks", subtitle: "Mark text for durable [[note]] link suggestions.", aliases: ["links", "wikilinks", "spelllinks", "backlinks", "connect"], group: .intelligence, markdownTemplate: "> [!note] Create Spelllinks\n> Suggest canonical [[links]] and missing notes."),
        MarkdownEditorCommand(id: "grimoire_continue_writing", title: "Continue Writing", subtitle: "Mark the cursor location for assisted continuation.", aliases: ["continue", "draft", "write", "expand"], group: .intelligence, markdownTemplate: "> [!note] Continue writing from here\n> Keep the tone and facts consistent."),
        MarkdownEditorCommand(id: "grimoire_related_context", title: "Related Context", subtitle: "Ask for related notes and prior context.", aliases: ["related", "context", "memory", "heads up"], group: .intelligence, markdownTemplate: "> [!note] Related context\n> Surface related notes, backlinks, and unresolved threads."),
        MarkdownEditorCommand(id: "grimoire_ai_prompt", title: "AI Prompt", subtitle: "Capture a reusable prompt block.", aliases: ["prompt", "ai", "llm", "instruction"], group: .intelligence, markdownTemplate: "```prompt\nSystem:\n\nUser:\n\nExpected:\n```")
    ]

    private static let mermaidPortableCommands: [MarkdownEditorCommand] = [
        MarkdownEditorCommand(id: "grimoire_mermaid", title: "Mermaid Diagram", subtitle: "Insert a fenced Mermaid flowchart.", aliases: ["diagram", "flowchart", "sequence", "chart", "mermaid"], group: .technical, markdownTemplate: "```mermaid\nflowchart TD\n  Idea[Idea] --> Draft[Draft]\n  Draft --> Review{Ready?}\n  Review -->|yes| Ship[Ship]\n  Review -->|no| Draft\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_flowchart", title: "Flowchart", subtitle: "Map a process or decision tree.", aliases: ["flow", "process", "decision tree", "diagram"], group: .technical, markdownTemplate: "```mermaid\nflowchart LR\n  Start([Start]) --> Capture[Capture]\n  Capture --> Link[[Spelllink notes]]\n  Link --> Done([Done])\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_sequence", title: "Sequence Diagram", subtitle: "Show messages across people, apps, or agents.", aliases: ["sequence", "messages", "protocol", "api flow"], group: .technical, markdownTemplate: "```mermaid\nsequenceDiagram\n  participant User\n  participant Grimoire\n  participant Agent\n  User->>Grimoire: Ask with context\n  Grimoire->>Agent: Send note snapshot\n  Agent-->>Grimoire: Stream answer\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_class", title: "Class Diagram", subtitle: "Sketch objects, models, and contracts.", aliases: ["class", "uml", "model", "schema"], group: .technical, markdownTemplate: "```mermaid\nclassDiagram\n  class Note {\n    +String title\n    +String path\n  }\n  class Spelllink {\n    +String target\n  }\n  Note --> Spelllink\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_state", title: "State Diagram", subtitle: "Describe states and transitions.", aliases: ["state", "workflow", "lifecycle", "fsm"], group: .technical, markdownTemplate: "```mermaid\nstateDiagram-v2\n  [*] --> Inbox\n  Inbox --> Drafting\n  Drafting --> Linked\n  Linked --> Archived\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_er", title: "ER Diagram", subtitle: "Map data relationships.", aliases: ["er", "database", "relation", "entity relationship"], group: .technical, markdownTemplate: "```mermaid\nerDiagram\n  NOTE ||--o{ SPELLLINK : contains\n  NOTE {\n    string title\n    string path\n  }\n  SPELLLINK {\n    string target\n  }\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_gantt", title: "Gantt Chart", subtitle: "Plan milestones over time.", aliases: ["gantt", "timeline plan", "schedule", "roadmap"], group: .technical, markdownTemplate: "```mermaid\ngantt\n  title Project Roadmap\n  dateFormat  YYYY-MM-DD\n  section Build\n  Editor polish :active, 2026-05-01, 5d\n  Agent bridge :2026-05-06, 4d\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_pie", title: "Pie Chart", subtitle: "Show rough proportions.", aliases: ["pie", "chart", "proportion", "breakdown"], group: .technical, markdownTemplate: "```mermaid\npie title Attention\n  \"Writing\" : 45\n  \"Linking\" : 30\n  \"Review\" : 25\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_journey", title: "Journey Map", subtitle: "Map a user or thinking journey.", aliases: ["journey", "user journey", "experience map"], group: .technical, markdownTemplate: "```mermaid\njourney\n  title Note-making flow\n  section Capture\n    Quick thought: 5: User\n    Add Spelllink: 4: User\n  section Reuse\n    Ask agent: 4: User, Agent\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_timeline", title: "Timeline", subtitle: "Capture events in chronological order.", aliases: ["timeline", "history", "events", "chronology"], group: .technical, markdownTemplate: "```mermaid\ntimeline\n  title Project history\n  2026-05-01 : Editor package split\n  2026-05-03 : Canvas contract\n  2026-05-07 : Visual refresh\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_mindmap", title: "Mindmap", subtitle: "Branch concepts from one idea.", aliases: ["mindmap", "brainstorm", "concept map", "map"], group: .technical, markdownTemplate: "```mermaid\nmindmap\n  root((Grimoire))\n    Markdown\n      Spelllinks\n      Mermaid\n    Canvas\n      Ink\n      Whiteboard\n    Agents\n      Claude\n      Codex\n      Chitragupta\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_use_case", title: "Use Case Diagram", subtitle: "Represent use cases as a Mermaid flowchart.", aliases: ["use case", "case diagram", "actor", "uml use case"], group: .technical, markdownTemplate: "```mermaid\nflowchart LR\n  User((Writer))\n  Agent((AI Agent))\n  User --> Create[Create note]\n  User --> Link[Link notes]\n  Agent --> Suggest[Suggest context]\n  Suggest --> Link\n```"),
        MarkdownEditorCommand(id: "grimoire_mermaid_git_graph", title: "Git Graph", subtitle: "Show branch and merge history.", aliases: ["git", "branch", "merge", "version graph"], group: .technical, markdownTemplate: "```mermaid\ngitGraph\n  commit id: \"start\"\n  branch feature\n  checkout feature\n  commit id: \"canvas\"\n  checkout main\n  merge feature\n```")
    ]

    private static let sadhanaPortableCommands: [MarkdownEditorCommand] = [
        MarkdownEditorCommand(id: "grimoire_sadhana_session", title: "Practice Session", subtitle: "Log a Spanda-style timed practice with moment context.", aliases: ["spanda", "sadhana", "practice", "session", "timer"], group: .practice, markdownTemplate: "## Practice Session - {today} {time}\n\nPractice\n- \n\nTimer\n- Start:\n- End:\n- Duration:\n\nContext\n- Location:\n- Hora:\n- Tithi:\n- Nakshatra:\n- Kala window:\n\nScore\n| Layer | Signal | Score |\n| --- | --- | --- |\n| Kala |  |  |\n| Hora |  |  |\n| Vara |  |  |\n| Tithi |  |  |\n| Rahu/Gulika/Yamaganda |  |  |\n\nNotes\n- "),
        MarkdownEditorCommand(id: "grimoire_panchanga_snapshot", title: "Panchanga Snapshot", subtitle: "Capture hora, tithi, nakshatra, kala, and caution windows.", aliases: ["panchanga", "hora", "tithi", "nakshatra", "rahu kalam"], group: .practice, markdownTemplate: "## Panchanga Snapshot - {today} {time}\n\n| Field | Value | Notes |\n| --- | --- | --- |\n| Location |  |  |\n| Sunrise |  |  |\n| Sunset |  |  |\n| Vara |  |  |\n| Hora |  |  |\n| Tithi |  |  |\n| Nakshatra |  |  |\n| Yoga |  |  |\n| Karana |  |  |\n| Brahma Muhurta |  |  |\n| Sandhya |  |  |\n| Rahu Kalam |  |  |"),
        MarkdownEditorCommand(id: "grimoire_japa_log", title: "Japa Log", subtitle: "Track mantra count, mala rounds, sankalpa, and after-state.", aliases: ["japa", "mantra", "mala", "108", "chant"], group: .practice, markdownTemplate: "## Japa Log - {today}\n\n| Mantra | Count | Mala | Hora | State |\n| --- | ---: | ---: | --- | --- |\n|  | 108 | 1 |  |  |\n\nSankalpa\n- \n\nAfter\n- "),
        MarkdownEditorCommand(id: "grimoire_pranayama_log", title: "Pranayama Log", subtitle: "Track breath ratio, rounds, duration, and nervous-system state.", aliases: ["pranayama", "breath", "nadi shodhana", "bhramari", "breathwork"], group: .practice, markdownTemplate: "## Pranayama Log - {today} {time}\n\n| Practice | Ratio | Rounds | Duration |\n| --- | --- | ---: | --- |\n| Nadi Shodhana | 4:4:8:4 |  |  |\n\nBefore\n- Breath:\n- Mind:\n\nAfter\n- Breath:\n- Mind:"),
        MarkdownEditorCommand(id: "grimoire_practice_prescription", title: "Practice Prescription", subtitle: "Compare practices by timing signal before choosing what to do.", aliases: ["prescriber", "score", "right practice", "jyotisha", "recommend"], group: .practice, markdownTemplate: "## Practice Prescription - {today}\n\n| Candidate | Type | Why now | Score |\n| --- | --- | --- | ---: |\n|  | Pranayama |  |  |\n|  | Mantra |  |  |\n|  | Dhyana |  |  |\n|  | Svadhyaya |  |  |\n\nDecision\n- [ ] Practice now\n- [ ] Defer\n- [ ] Avoid due to timing")
    ]
}
