import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('folder glyph CSS', () => {
  it('frames left-sidebar folders as quiet semantic medallions', () => {
    const css = readFileSync(`${process.cwd()}/src/components/folder-tree/FolderGlyph.css`, 'utf8')

    expect(css).toContain('.folder-glyph')
    expect(css).toContain('.folder-glyph__icon')
    expect(css).toContain('[data-folder-glyph-tone="veda"]')
    expect(css).toContain('[data-folder-glyph-tone="shaastra"]')
    expect(css).toContain('[data-folder-glyph-tone="purana"]')
    expect(css).toContain('[data-folder-glyph-tone="rishi"]')
    expect(css).toContain('[data-folder-glyph-tone="brain"]')
    expect(css).toContain('[data-folder-glyph-tone="star"]')
    expect(css).toContain('[data-folder-glyph-tone="agent"]')
    expect(css).toContain('[data-folder-glyph-tone="storage"]')
    expect(css).toContain('[data-folder-glyph-tone="docs"]')
    expect(css).toContain('[data-folder-glyph-tone="dev"]')
    expect(css).toContain('[data-folder-glyph-tone="data"]')
    expect(css).toContain('[data-folder-glyph-tone="journal"]')
    expect(css).toContain('[data-folder-glyph-tone="vault"]')
    expect(css).toContain('[data-folder-glyph-tone="private"]')
    expect(css).toContain('[data-folder-glyph-tone="research"]')
    expect(css).toContain('[data-folder-glyph-tone="template"]')
    expect(css).not.toContain('data-folder-glyph-motif')
    expect(css).not.toContain('.folder-glyph__route')
    expect(css).not.toContain('.folder-glyph__thread')
    expect(css).not.toContain('.folder-glyph__bead')
    expect(css).not.toContain('.folder-glyph__spark')
    expect(css).not.toContain('.folder-glyph__constellation')
    expect(css).not.toContain('.folder-glyph__cel-glint')
    expect(css).not.toContain('--folder-glyph-secondary')
    expect(css).not.toContain('--folder-glyph-warm')
    expect(css).not.toContain('conic-gradient')
    expect(css).not.toContain('radial-gradient')
    expect(css).not.toContain('drop-shadow')
    expect(css).not.toContain('accent-teal')
    expect(css).not.toContain('accent-green')
    expect(css).toContain('box-shadow: none')
    expect(css).not.toContain('@keyframes folder-glyph-route-arrive')
    expect(css).not.toContain('@keyframes folder-glyph-signal-pop')
    expect(css).not.toContain('animation: folder-glyph')
    expect(css).toContain('prefers-reduced-motion: reduce')
  })
})
