import { useAppCommands } from '../hooks/useAppCommands'
import type { EntryWorkspace } from './useEntryWorkspace'
import type { GitWorkflow } from './useGitWorkflow'
import type { NoteWorkspace } from './useNoteWorkspace'
import type { AppShellState } from './useAppShellState'
import type { VaultFoundation } from './useVaultFoundation'

export function useAppCommandRegistry(
  foundation: VaultFoundation,
  workspace: NoteWorkspace,
  entryWorkspace: EntryWorkspace,
  gitWorkflow: GitWorkflow,
  shell: AppShellState,
) {
  const {
    aiAgentPreferences, aiAgentsStatus, appLocale, cloneGettingStartedVault, dialogs,
    effectiveSelection, explicitOrganizationEnabled, handleSetSelection, handleSetUiLanguage, isGitVault,
    mcpStatus, multiSelectionCommandRef, noteListFilter, openAudioRecordingDialog,
    openCreateVaultDialog, openFeedback, openGraphModal, openMcpSetupDialog, selectedUiLanguage,
    setNoteListFilter, systemLocale, vault, vaultAiGuidanceStatus, vaultSwitcher, visibleNotesRef,
  } = foundation
  const {
    appSave, autoSync, canAddRemote, canGoBack, canGoForward, conflictFlow, handleGoBack,
    handleGoForward, notes,
  } = workspace
  const {
    folderActions, handleCustomizeNoteListColumns, handleOpenInNewWindow,
    handlePreviewNoteWithQuickLook, handleRemoveNoteIconCommand, handleRevealNoteInFinder,
    handleRevealVaultInFinder, handleSetNoteIconCommand,
  } = entryWorkspace
  const { deleteActions, entryActions, handleCommitPush } = gitWorkflow
  const {
    activeDeletedFile, activeNoteHasIcon, activeNoteModified, audioTranscription,
    canCustomizeNoteListColumns, changeNoteTypeCommand, handleCaptureDreamCommand,
    handleCaptureJournalCommand, handleCaptureThoughtCommand, handleCheckForUpdates,
    handleRepairVault, handleSetViewMode, handleToggleInspector, insertWeatherSnapshotCommand,
    moveNoteToFolderCommand, noteLayout, noteListColumnsLabel, removeActiveVaultCommand,
    restoreDeletedNoteCommand, restoreVaultAiGuidanceCommand, toggleDiffCommand,
    toggleNoteLayout, toggleOrganizedCommand, toggleRawEditorCommand, zoom, noteRetargetingUi,
  } = shell
  const commands = useAppCommands({
    activeTabPath: notes.activeTabPath, activeTabPathRef: notes.activeTabPathRef,
    entries: vault.entries,
    visibleNotesRef,
    multiSelectionCommandRef,
    modifiedCount: isGitVault ? vault.modifiedFiles.length : 0,
    isGitVault,
    activeNoteModified,
    selection: effectiveSelection,
    onQuickOpen: dialogs.openQuickOpen, onCommandPalette: dialogs.openCommandPalette,
    onSearch: dialogs.openSearch,
    onCreateNote: notes.handleCreateNoteImmediate,
    onCaptureThought: handleCaptureThoughtCommand,
    onCaptureJournal: handleCaptureJournalCommand,
    onCaptureDream: handleCaptureDreamCommand,
    onCreateNoteOfType: notes.handleCreateNoteImmediate,
    onSave: appSave.handleSave,
    onOpenSettings: dialogs.openSettings,
    onOpenFeedback: openFeedback,
    onDeleteNote: deleteActions.handleDeleteNote,
    onArchiveNote: entryActions.handleArchiveNote, onUnarchiveNote: entryActions.handleUnarchiveNote,
    onCommitPush: handleCommitPush,
    onPull: autoSync.triggerSync,
    onResolveConflicts: conflictFlow.handleOpenConflictResolver,
    onSetViewMode: handleSetViewMode,
    onToggleInspector: handleToggleInspector,
    onToggleDiff: toggleDiffCommand,
    onToggleRawEditor: toggleRawEditorCommand,
    onOpenGraph: openGraphModal,
    noteLayout,
    onToggleNoteLayout: toggleNoteLayout,
    onZoomIn: zoom.zoomIn, onZoomOut: zoom.zoomOut, onZoomReset: zoom.zoomReset,
    zoomLevel: zoom.zoomLevel,
    onSelect: handleSetSelection,
    onRenameFolder: folderActions.renameSelectedFolder,
    onDeleteFolder: folderActions.deleteSelectedFolder,
    showInbox: explicitOrganizationEnabled,
    onReplaceActiveTab: notes.handleReplaceActiveTab,
    onSelectNote: notes.handleSelectNote,
    onGoBack: handleGoBack, onGoForward: handleGoForward,
    canGoBack: canGoBack, canGoForward: canGoForward,
    onOpenVault: vaultSwitcher.handleOpenLocalFolder,
    onCreateEmptyVault: openCreateVaultDialog,
    canAddRemote,
    onCreateType: dialogs.openCreateType,
    onToggleAIChat: dialogs.toggleAIChat,
    onCheckForUpdates: handleCheckForUpdates,
    onRemoveActiveVault: removeActiveVaultCommand,
    onRestoreGettingStarted: cloneGettingStartedVault,
    isGettingStartedHidden: vaultSwitcher.isGettingStartedHidden,
    vaultCount: vaultSwitcher.allVaults.length,
    locale: appLocale,
    systemLocale,
    selectedUiLanguage,
    onSetUiLanguage: handleSetUiLanguage,
    mcpStatus,
    onInstallMcp: openMcpSetupDialog,
    onOpenAiAgents: dialogs.openSettings,
    aiAgentsStatus,
    vaultAiGuidanceStatus,
    onRestoreVaultAiGuidance: restoreVaultAiGuidanceCommand,
    selectedAiAgent: aiAgentPreferences.defaultAiAgent,
    onSetDefaultAiAgent: aiAgentPreferences.setDefaultAiAgent,
    onCycleDefaultAiAgent: aiAgentPreferences.cycleDefaultAiAgent,
    selectedAiAgentLabel: aiAgentPreferences.defaultAiAgentLabel,
    onReloadVault: vault.reloadVault,
    onRepairVault: handleRepairVault,
    onSetNoteIcon: handleSetNoteIconCommand,
    onRemoveNoteIcon: handleRemoveNoteIconCommand,
    onChangeNoteType: changeNoteTypeCommand,
    onMoveNoteToFolder: moveNoteToFolderCommand,
    canMoveNoteToFolder: noteRetargetingUi.canMoveActiveNoteToFolder,
    activeNoteHasIcon,
    noteListFilter,
    onSetNoteListFilter: setNoteListFilter,
    onOpenInNewWindow: handleOpenInNewWindow,
    onRevealNoteInFinder: handleRevealNoteInFinder,
    onPreviewNoteWithQuickLook: handlePreviewNoteWithQuickLook,
    onRevealVaultInFinder: handleRevealVaultInFinder,
    onToggleFavorite: entryActions.handleToggleFavorite,
    onToggleOrganized: toggleOrganizedCommand,
    onInsertWeatherSnapshot: insertWeatherSnapshotCommand,
    onTranscribeAudio: audioTranscription.transcribePickedAudio,
    onRecordAudio: openAudioRecordingDialog,
    onCustomizeNoteListColumns: handleCustomizeNoteListColumns,
    canCustomizeNoteListColumns,
    noteListColumnsLabel,
    onRestoreDeletedNote: restoreDeletedNoteCommand,
    canRestoreDeletedNote: !!activeDeletedFile,
  })
  return commands
}
