import { render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import { SidebarArtwork } from './SidebarArtwork'

describe('SidebarArtwork', () => {
  it('renders a single quiet Grimoire vault-atlas sigil for theme CSS to tint', () => {
    render(<SidebarArtwork />)

    expect(screen.getByTestId('sidebar-artwork')).toBeInTheDocument()
    expect(document.querySelector('[data-sidebar-glyph="grimoire-sigil"]')).toBeInTheDocument()
    expect(document.querySelectorAll('[data-sidebar-glyph]')).toHaveLength(1)
    expect(document.querySelector('.sidebar-artwork__glyph--sigil')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__glyph--vault-atlas')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__glyph--living-grimoire')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__atlas-frame')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__atlas-ridge')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__atlas-shadow')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__gate')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__vault-arch')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__compass')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__page')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__page--right')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__aurora')).toBeInTheDocument()
    expect(document.querySelector('[data-sidebar-art-channel="living-routes"]')).toBeInTheDocument()
    expect(document.querySelectorAll('.sidebar-artwork__signal-line')).toHaveLength(2)
    expect(document.querySelectorAll('.sidebar-artwork__signal-orb')).toHaveLength(3)
    expect(document.querySelector('.sidebar-artwork__ribbon--veda')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__ribbon--shastra')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__palm-leaf--veda')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__palm-leaf--shastra')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__purana-scroll')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__core-glow')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__local-dot')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__living-crest')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__rishi-aura')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__rishi-seat')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__brain-loop')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__second-brain')).toBeInTheDocument()
    expect(document.querySelectorAll('.sidebar-artwork__brain-node')).toHaveLength(4)
    expect(document.querySelector('.sidebar-artwork__orbit')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__route')).toBeInTheDocument()
    expect(document.querySelector('[data-sidebar-art-channel="source-routes"]')).toBeInTheDocument()
    expect(document.querySelectorAll('.sidebar-artwork__route-beam')).toHaveLength(2)
    expect(document.querySelectorAll('.sidebar-artwork__route-node')).toHaveLength(3)
    expect(document.querySelector('[data-sidebar-art-channel="foreground-pouch-intake"]')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__pouch-overlay')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__aura')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__body')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__mouth')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__throat')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__cavity')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__swallow')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__lip')).toBeInTheDocument()
    expect(document.querySelectorAll('.sidebar-pouch-overlay__cloud')).toHaveLength(3)
    expect(document.querySelectorAll('.sidebar-pouch-overlay__wisp')).toHaveLength(2)
    expect(document.querySelector('.sidebar-pouch-overlay__funnel')).toBeInTheDocument()
    expect(document.querySelectorAll('.sidebar-pouch-overlay__stream')).toHaveLength(3)
    expect(document.querySelector('.sidebar-pouch-overlay__stream--left')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-pouch-overlay__stream--right')).toBeInTheDocument()
    expect(document.querySelectorAll('.sidebar-pouch-overlay__particle')).toHaveLength(3)
    expect(document.querySelector('.sidebar-artwork__constellation')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__memory-line')).toBeInTheDocument()
    expect(document.querySelectorAll('.sidebar-artwork__node')).toHaveLength(7)
    expect(document.querySelector('.sidebar-artwork__spark-crown')).toBeInTheDocument()
    expect(document.querySelectorAll('[data-sidebar-art-mark]')).toHaveLength(5)
    expect(document.querySelectorAll('.sidebar-artwork__token-aura')).toHaveLength(5)
    expect(document.querySelector('[data-sidebar-art-mark="vedas"]')).toBeInTheDocument()
    expect(document.querySelector('[data-sidebar-art-mark="shaastras"]')).toBeInTheDocument()
    expect(document.querySelector('[data-sidebar-art-mark="puranas"]')).toBeInTheDocument()
    expect(document.querySelector('[data-sidebar-art-mark="rishi"]')).toBeInTheDocument()
    expect(document.querySelector('[data-sidebar-art-mark="second-brain"]')).toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__keeper')).not.toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__vine')).not.toBeInTheDocument()
    expect(document.querySelector('.sidebar-artwork__leaf')).not.toBeInTheDocument()
  })

  it('keeps decorative glyphs textless so narrow sidebars cannot jumble copy', () => {
    render(<SidebarArtwork />)

    expect(screen.queryByText('Vault map')).not.toBeInTheDocument()
    expect(screen.queryByText('Local notes')).not.toBeInTheDocument()
    expect(screen.queryByText(/Grimoire Agent|Observing|Ready/i)).not.toBeInTheDocument()
  })

  it('uses a compact test id for appearance previews', () => {
    render(<SidebarArtwork compact />)

    expect(screen.getByTestId('settings-sidebar-artwork-preview')).toBeInTheDocument()
  })
})
