// Generates a tintable React glyph registry from the Grimoire glyph pack.
//
// Reads assets/grimoire-glyph-pack/svg/template/*.svg (167 single-colour line
// glyphs), rewrites the hardcoded ink (#0B1F2A) to `currentColor` so each glyph
// tints with CSS `color` per light/dark/retro theme, strips <title>/<desc> and
// the outer <svg> wrapper, and emits src/components/glyphs/glyphData.ts with the
// inner markup keyed by the gm_-stripped name plus a GlyphName union type.
//
// The handful of semantic status colours (#EF4444 error, #22C55E success,
// #F97316 / #4A90E2 / #F43F5E) are intentional and left literal.
//
// Run: node scripts/generate-glyphs.mjs

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const srcDir = join(root, 'assets/grimoire-glyph-pack/svg/template')
const outFile = join(root, 'src/components/glyphs/glyphData.ts')

const INK = /#0B1F2A/gi

/** Strip the outer <svg>, <title>, <desc>; return tinted inner markup on one line. */
function innerMarkup(svg) {
  return svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/i, '')
    .replace(/<\/svg>/i, '')
    .replace(/<title>[\s\S]*?<\/title>/gi, '')
    .replace(/<desc>[\s\S]*?<\/desc>/gi, '')
    .replace(INK, 'currentColor')
    .replace(/\s+/g, ' ')
    .trim()
}

/** gm_new_note -> newNote, gm_ai_agent -> aiAgent, gm_import -> import. */
function camelKey(file) {
  const base = file.replace(/\.svg$/, '').replace(/^gm_/, '')
  return base.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase())
}

const files = readdirSync(srcDir).filter((f) => f.endsWith('.svg')).sort()
const entries = files.map((f) => [camelKey(f), innerMarkup(readFileSync(join(srcDir, f), 'utf8'))])

const body = entries.map(([k, m]) => `  ${JSON.stringify(k)}: ${JSON.stringify(m)},`).join('\n')
const out = `// AUTO-GENERATED by scripts/generate-glyphs.mjs — do not edit by hand.
// Source: assets/grimoire-glyph-pack/svg/template (Grimoire glyph pack, ${entries.length} glyphs).
// Run \`node scripts/generate-glyphs.mjs\` to regenerate.

/** Inner SVG markup for each Grimoire glyph, tinted via \`currentColor\`. */
export const GLYPH_MARKUP = {
${body}
} as const

/** Union of every available Grimoire glyph name. */
export type GlyphName = keyof typeof GLYPH_MARKUP
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, out)
console.log(`Wrote ${entries.length} glyphs -> ${outFile}`)
