/**
 * Mock vault entries and bulk entry generator.
 * Provides realistic VaultEntry[] data for browser dev mode.
 */

import type { VaultEntry } from '../types'

const now = Date.now() / 1000

type MockEntrySeed = {
  filename: string
  title: string
  isA: string
  aliases?: string[]
  belongsTo?: string[]
  relatedTo?: string[]
  status?: string | null
  archived?: boolean
  modifiedAt: number | null
  createdAt: number | null
  fileSize: number
  snippet: string
  wordCount: number
  relationships?: Record<string, string[]>
  icon?: string | null
  color?: string | null
  order?: number | null
  sidebarLabel?: string | null
  template?: string | null
  sort?: string | null
  view?: string | null
  visible?: boolean | null
  outgoingLinks?: string[]
  properties?: VaultEntry['properties']
  organized?: boolean
  favorite?: boolean
  favoriteIndex?: number | null
  listPropertiesDisplay?: string[]
  hasH1?: boolean
}

function mockEntry(seed: MockEntrySeed): VaultEntry {
  return {
    path: `/Users/srinivas/Grimoire/${seed.filename}`,
    filename: seed.filename,
    title: seed.title,
    isA: seed.isA,
    aliases: seed.aliases ?? [],
    belongsTo: seed.belongsTo ?? [],
    relatedTo: seed.relatedTo ?? [],
    status: seed.status ?? null,
    archived: seed.archived ?? false,
    modifiedAt: seed.modifiedAt,
    createdAt: seed.createdAt,
    fileSize: seed.fileSize,
    snippet: seed.snippet,
    wordCount: seed.wordCount,
    relationships: seed.relationships ?? {},
    icon: seed.icon ?? null,
    color: seed.color ?? null,
    order: seed.order ?? null,
    sidebarLabel: seed.sidebarLabel ?? null,
    template: seed.template ?? null,
    sort: seed.sort ?? null,
    view: seed.view ?? null,
    visible: seed.visible ?? null,
    outgoingLinks: seed.outgoingLinks ?? [],
    properties: seed.properties ?? {},
    organized: seed.organized ?? false,
    favorite: seed.favorite ?? false,
    favoriteIndex: seed.favoriteIndex ?? null,
    listPropertiesDisplay: seed.listPropertiesDisplay ?? [],
    hasH1: seed.hasH1 ?? false,
  }
}

const LEARNING_PROJECT = '[[grimoire-learning-project]]'
const FEATURE_TOUR = '[[grimoire-feature-tour]]'

const LEARNING_GUIDE_ENTRIES: VaultEntry[] = [
  mockEntry({
    filename: 'grimoire-learning-project.md',
    title: 'Grimoire Feature Showcase',
    isA: 'Project',
    aliases: ['Grimoire Learning Project', 'Grimoire Feature Showcase', 'Ship Grimoire with a demo vault'],
    belongsTo: ['[[25q2]]'],
    relatedTo: [
      FEATURE_TOUR,
      '[[grimoire-start-here]]',
      '[[grimoire-markdown-learning]]',
      '[[grimoire-properties-and-types]]',
      '[[grimoire-search-and-commands]]',
      '[[grimoire-journal-demo-2026-05-31]]',
      '[[grimoire-dream-demo-2026-05-31]]',
      '[[grimoire-links-and-backlinks]]',
      '[[grimoire-console-and-agents]]',
      '[[grimoire-agent-council]]',
      '[[grimoire-local-agent-map]]',
      '[[grimoire-canvas-and-attachments]]',
      '[[grimoire-crystallize-example]]',
      '[[grimoire-audio-transcription]]',
      '[[grimoire-privacy-and-memory]]',
      '[[grimoire-portability-and-sync]]',
      '[[grimoire-settings-and-themes]]',
    ],
    status: 'Active',
    modifiedAt: now - 60,
    createdAt: now - 86400,
    fileSize: 4200,
    snippet: 'A shippable in-vault feature showcase for Markdown, journals, dreams, links, properties, search, canvases, audio, agents, privacy, themes, and portability.',
    wordCount: 560,
    relationships: {
      'Belongs to': ['[[25q2]]'],
      'Related to': [FEATURE_TOUR, '[[grimoire-start-here]]', '[[grimoire-markdown-learning]]', '[[grimoire-console-and-agents]]', '[[grimoire-agent-council]]', '[[grimoire-local-agent-map]]'],
      'Type': ['[[project]]'],
    },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-start-here', 'grimoire-markdown-learning', 'grimoire-console-and-agents', 'grimoire-agent-council', 'grimoire-local-agent-map'],
    properties: { Priority: 'High', Owner: 'Srinivas Pendela' },
  }),
  mockEntry({
    filename: 'grimoire-feature-tour.md',
    title: 'Grimoire Feature Tour',
    isA: 'Note',
    aliases: ['Feature Tour', 'Grimoire Feature Tour'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [
      '[[grimoire-start-here]]',
      '[[grimoire-markdown-learning]]',
      '[[grimoire-properties-and-types]]',
      '[[grimoire-search-and-commands]]',
      '[[grimoire-links-and-backlinks]]',
      '[[grimoire-journal-demo-2026-05-31]]',
      '[[grimoire-dream-demo-2026-05-31]]',
      '[[grimoire-canvas-and-attachments]]',
      '[[grimoire-audio-transcription]]',
      '[[grimoire-console-and-agents]]',
      '[[grimoire-agent-council]]',
      '[[grimoire-local-agent-map]]',
      '[[grimoire-privacy-and-memory]]',
      '[[grimoire-portability-and-sync]]',
      '[[grimoire-settings-and-themes]]',
    ],
    status: 'Active',
    modifiedAt: now - 90,
    createdAt: now - 86400,
    fileSize: 3600,
    snippet: 'Launch-day checklist mapping every major Grimoire surface to an editable demo note.',
    wordCount: 520,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': ['[[grimoire-start-here]]'], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-start-here', 'grimoire-markdown-learning', 'grimoire-properties-and-types', 'grimoire-search-and-commands'],
    properties: { Priority: 'High' },
  }),
  mockEntry({
    filename: 'grimoire-start-here.md',
    title: 'Start Here - Learn Grimoire',
    isA: 'Note',
    aliases: ['Start Here - Learn Grimoire'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-markdown-learning]]', '[[grimoire-links-and-backlinks]]'],
    status: 'Active',
    modifiedAt: now - 120,
    createdAt: now - 86400,
    fileSize: 1650,
    snippet: 'A guided first note for learning Grimoire by opening the feature tour, Markdown, properties, Journal, Dream, console, canvas, and agent examples.',
    wordCount: 285,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-markdown-learning', 'grimoire-properties-and-types', 'grimoire-links-and-backlinks', 'grimoire-console-and-agents'],
  }),
  mockEntry({
    filename: 'grimoire-markdown-learning.md',
    title: 'Markdown Learning',
    isA: 'Note',
    aliases: ['Markdown Learning'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: ['[[grimoire-start-here]]', '[[grimoire-links-and-backlinks]]'],
    status: 'Active',
    modifiedAt: now - 180,
    createdAt: now - 86400,
    fileSize: 2450,
    snippet: 'Learn headings, emphasis, lists, tasks, wikilinks, code blocks, and frontmatter using editable Markdown examples.',
    wordCount: 420,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': ['[[grimoire-links-and-backlinks]]'], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-links-and-backlinks', 'grimoire-learning-project'],
  }),
  mockEntry({
    filename: 'grimoire-properties-and-types.md',
    title: 'Properties and Types',
    isA: 'Note',
    aliases: ['Properties and Types'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-markdown-learning]]'],
    status: 'Active',
    modifiedAt: now - 210,
    createdAt: now - 86400,
    fileSize: 1450,
    snippet: 'Frontmatter, custom types, icons, colors, owner, status, priority, and property panels shown as portable Markdown.',
    wordCount: 220,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-markdown-learning', 'journal', 'dream', 'console', 'agent'],
    properties: { Priority: 'High', Owner: 'Srinivas Pendela', color: 'green' },
  }),
  mockEntry({
    filename: 'grimoire-search-and-commands.md',
    title: 'Search and Commands',
    isA: 'Note',
    aliases: ['Search and Commands'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-links-and-backlinks]]'],
    status: 'Active',
    modifiedAt: now - 225,
    createdAt: now - 86400,
    fileSize: 1000,
    snippet: 'Quick Open, command palette, note search, and document find tested against real demo notes.',
    wordCount: 160,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-canvas-and-attachments'],
  }),
  mockEntry({
    filename: 'grimoire-journal-demo-2026-05-31.md',
    title: 'Journal Demo - 2026-05-31',
    isA: 'Journal',
    aliases: ['Journal Demo - 2026-05-31'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-dream-demo-2026-05-31]]'],
    status: null,
    modifiedAt: now - 240,
    createdAt: now - 86400,
    fileSize: 1300,
    snippet: 'A May 31 launch-day local-first journal entry showing daily capture, reflection, project links, and privacy frontmatter.',
    wordCount: 250,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR, '[[grimoire-dream-demo-2026-05-31]]'], 'Type': ['[[journal]]'] },
    outgoingLinks: ['grimoire-learning-project', 'grimoire-feature-tour', 'grimoire-dream-demo-2026-05-31', 'person-srinivas-pendela'],
    properties: { date: '2026-05-31', locality: 'local-first', 'egress-blocked': true },
  }),
  mockEntry({
    filename: 'grimoire-dream-demo-2026-05-31.md',
    title: 'Dream Demo - 2026-05-31',
    isA: 'Dream',
    aliases: ['Dream Demo - 2026-05-31'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-journal-demo-2026-05-31]]'],
    status: null,
    modifiedAt: now - 300,
    createdAt: now - 86400,
    fileSize: 1200,
    snippet: 'A dated dream entry with symbols, interpretation, and a backlink to the matching journal context.',
    wordCount: 215,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR, '[[grimoire-journal-demo-2026-05-31]]'], 'Type': ['[[dream]]'] },
    outgoingLinks: ['grimoire-journal-demo-2026-05-31', 'grimoire-feature-tour', 'grimoire-links-and-backlinks'],
    properties: { date: '2026-05-31', symbols: ['library', 'door', 'river'], locality: 'local-first' },
  }),
  mockEntry({
    filename: 'grimoire-links-and-backlinks.md',
    title: 'Links and Backlinks',
    isA: 'Note',
    aliases: ['Links and Backlinks'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: ['[[grimoire-markdown-learning]]'],
    status: 'Active',
    modifiedAt: now - 360,
    createdAt: now - 86400,
    fileSize: 1500,
    snippet: 'A practical lesson on wikilinks, backlinks, belongs_to, related_to, and project context inside a Markdown vault.',
    wordCount: 280,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': ['[[grimoire-markdown-learning]]'], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-learning-project', 'grimoire-markdown-learning'],
  }),
  mockEntry({
    filename: 'grimoire-console-and-agents.md',
    title: 'Console and Agents',
    isA: 'Console',
    aliases: ['Console and Agents'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: ['[[grimoire-local-agent-map]]', '[[grimoire-agent-council]]'],
    status: 'Active',
    modifiedAt: now - 420,
    createdAt: now - 86400,
    fileSize: 1450,
    snippet: 'Command snippets and local agent request patterns kept beside the project they support, without storing secrets.',
    wordCount: 260,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': ['[[grimoire-local-agent-map]]', '[[grimoire-agent-council]]'], 'Type': ['[[console]]'] },
    outgoingLinks: ['grimoire-local-agent-map', 'grimoire-agent-council', 'grimoire-markdown-learning'],
  }),
  mockEntry({
    filename: 'grimoire-agent-council.md',
    title: 'Agent Council',
    isA: 'Agent',
    aliases: ['Agent Council'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: ['[[grimoire-feature-tour]]', '[[grimoire-local-agent-map]]', '[[grimoire-privacy-and-memory]]', '[[grimoire-crystallize-example]]'],
    status: 'Active',
    modifiedAt: now - 450,
    createdAt: now - 86400,
    fileSize: 2400,
    snippet: 'Source-safe Council lanes, readiness states, review-gated synthesis, and the honest boundary before full live multi-agent fan-out.',
    wordCount: 360,
    relationships: {
      'Belongs to': [LEARNING_PROJECT],
      'Related to': ['[[grimoire-feature-tour]]', '[[grimoire-local-agent-map]]', '[[grimoire-privacy-and-memory]]', '[[grimoire-crystallize-example]]'],
      'Type': ['[[agent]]'],
    },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-local-agent-map', 'grimoire-privacy-and-memory', 'grimoire-crystallize-example'],
    properties: { locality: 'local-first', 'egress-blocked': true },
  }),
  mockEntry({
    filename: 'grimoire-local-agent-map.md',
    title: 'Local Agent Map',
    isA: 'Agent',
    aliases: ['Local Agent Map'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: ['[[grimoire-console-and-agents]]', '[[grimoire-agent-council]]'],
    status: 'Planned',
    modifiedAt: now - 480,
    createdAt: now - 86400,
    fileSize: 1150,
    snippet: 'A local-first map of Claude Code, Codex, and Chitragupta lanes with boundaries for writes, scope, and approvals.',
    wordCount: 220,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': ['[[grimoire-console-and-agents]]', '[[grimoire-agent-council]]'], 'Type': ['[[agent]]'] },
    outgoingLinks: ['grimoire-console-and-agents', 'grimoire-agent-council'],
    properties: { locality: 'local-first', 'egress-blocked': true },
  }),
  mockEntry({
    filename: 'grimoire-canvas-and-attachments.md',
    title: 'Canvas and Attachments',
    isA: 'Note',
    aliases: ['Canvas and Attachments'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: ['[[grimoire-qa-reference]]'],
    status: 'Active',
    modifiedAt: now - 540,
    createdAt: now - 86400,
    fileSize: 1100,
    snippet: 'A short guide to sketches, attachments, image references, and keeping visual artifacts linked to Markdown notes.',
    wordCount: 190,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': ['[[grimoire-qa-reference]]'], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-qa-reference', 'grimoire-learning-project'],
  }),
  mockEntry({
    filename: 'grimoire-crystallize-example.md',
    title: 'Crystallize Example',
    isA: 'Note',
    aliases: ['Crystallize Example'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: ['[[grimoire-journal-demo-2026-05-31]]', '[[grimoire-dream-demo-2026-05-31]]'],
    status: 'Draft',
    modifiedAt: now - 600,
    createdAt: now - 86400,
    fileSize: 1000,
    snippet: 'An example of turning loose journal and dream capture into a durable project note.',
    wordCount: 175,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': ['[[grimoire-journal-demo-2026-05-31]]'], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-journal-demo-2026-05-31', 'grimoire-dream-demo-2026-05-31', 'grimoire-learning-project'],
  }),
  mockEntry({
    filename: 'grimoire-audio-transcription.md',
    title: 'Audio Transcription',
    isA: 'Note',
    aliases: ['Audio Transcription'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-privacy-and-memory]]'],
    status: 'Active',
    modifiedAt: now - 615,
    createdAt: now - 86400,
    fileSize: 1200,
    snippet: 'Audio import and recording flow through local-first transcription, raw transcript notes, and cleaned summaries.',
    wordCount: 190,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-privacy-and-memory'],
    properties: { locality: 'local-first', 'egress-blocked': true },
  }),
  mockEntry({
    filename: 'grimoire-privacy-and-memory.md',
    title: 'Privacy and Memory',
    isA: 'Note',
    aliases: ['Privacy and Memory'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-local-agent-map]]', '[[grimoire-audio-transcription]]'],
    status: 'Active',
    modifiedAt: now - 630,
    createdAt: now - 86400,
    fileSize: 1250,
    snippet: 'Locality Firewall and Memory Ledger examples for safe agent context without leaking private notes.',
    wordCount: 210,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-local-agent-map', 'grimoire-journal-demo-2026-05-31'],
    properties: { locality: 'local-first', 'egress-blocked': true },
  }),
  mockEntry({
    filename: 'grimoire-portability-and-sync.md',
    title: 'Portability and Sync',
    isA: 'Note',
    aliases: ['Portability and Sync'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-markdown-learning]]'],
    status: 'Active',
    modifiedAt: now - 645,
    createdAt: now - 86400,
    fileSize: 1150,
    snippet: 'Git, import/export, portable bundles, capsules, and object-storage readiness as local-first product surfaces.',
    wordCount: 180,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-markdown-learning'],
    properties: { locality: 'local-first' },
  }),
  mockEntry({
    filename: 'grimoire-settings-and-themes.md',
    title: 'Settings and Themes',
    isA: 'Note',
    aliases: ['Settings and Themes'],
    belongsTo: [LEARNING_PROJECT],
    relatedTo: [FEATURE_TOUR, '[[grimoire-properties-and-types]]'],
    status: 'Active',
    modifiedAt: now - 650,
    createdAt: now - 86400,
    fileSize: 1100,
    snippet: 'Themes, typography, provider settings, API key boundaries, privacy, workflow, sync, and appearance settings.',
    wordCount: 175,
    relationships: { 'Belongs to': [LEARNING_PROJECT], 'Related to': [FEATURE_TOUR], 'Type': ['[[note]]'] },
    outgoingLinks: ['grimoire-feature-tour', 'grimoire-properties-and-types'],
  }),
  mockEntry({
    filename: 'journal.md',
    title: 'Journal',
    isA: 'Type',
    modifiedAt: now - 660,
    createdAt: now - 86400,
    fileSize: 320,
    snippet: 'Journal entries capture dated, private daily reflections.',
    wordCount: 40,
    relationships: {},
    icon: 'notebook',
    color: 'teal',
    sidebarLabel: 'Journal',
  }),
  mockEntry({
    filename: 'dream.md',
    title: 'Dream',
    isA: 'Type',
    modifiedAt: now - 720,
    createdAt: now - 86400,
    fileSize: 300,
    snippet: 'Dream entries capture recall, symbols, and interpretations.',
    wordCount: 38,
    relationships: {},
    icon: 'moon',
    color: 'purple',
    sidebarLabel: 'Dreams',
  }),
  mockEntry({
    filename: 'agent.md',
    title: 'Agent',
    isA: 'Type',
    modifiedAt: now - 780,
    createdAt: now - 86400,
    fileSize: 310,
    snippet: 'Agents describe local assistants, CLI lanes, and repeatable AI workflows.',
    wordCount: 36,
    relationships: {},
    icon: 'bot',
    color: 'cyan',
    sidebarLabel: 'Agents',
  }),
  mockEntry({
    filename: 'console.md',
    title: 'Console',
    isA: 'Type',
    modifiedAt: now - 840,
    createdAt: now - 86400,
    fileSize: 300,
    snippet: 'Console notes collect command snippets and repeatable checks.',
    wordCount: 34,
    relationships: {},
    icon: 'terminal',
    color: 'slate',
    sidebarLabel: 'Consoles',
  }),
]

export const MOCK_ENTRIES: VaultEntry[] = [
  ...LEARNING_GUIDE_ENTRIES,
  {
    path: '/Users/srinivas/Grimoire/26q1-grimoire-app.md',
    filename: '26q1-grimoire-app.md',
    title: 'Build Grimoire App',
    isA: 'Project',
    aliases: ['Grimoire App'],
    belongsTo: ['[[q1-2026]]'],
    relatedTo: ['[[software-development]]'],
    status: 'Active',
    archived: false,
    modifiedAt: now,
    createdAt: now - 86400 * 60,
    fileSize: 2048,
    snippet: 'This paragraph has bold text, italic text, bold italic, strikethrough, and inline code. Here\'s a regular link and a wiki-link to Karthik Reddy.',
    wordCount: 342,
    relationships: {
      'Belongs to': ['[[q1-2026]]'],
      'Related to': ['[[software-development]]'],
      'Type': ['[[project]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['q1-2026', 'software-development', 'karthik-reddy', 'meera-krishnan', 'arun-kumar'],
    properties: { Priority: 'High', 'Due date': '2026-06-15', Owner: 'Srinivas Pendela' },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/grow-newsletter.md',
    filename: 'grow-newsletter.md',
    title: 'Grow Newsletter',
    isA: 'Responsibility',
    aliases: [],
    belongsTo: [],
    relatedTo: ['[[growth]]'],
    status: 'Active',
    archived: false,
    modifiedAt: now - 3600,
    createdAt: now - 86400 * 180,
    fileSize: 1024,
    snippet: 'Build a sustainable audience through high-quality weekly essays on engineering leadership, AI, and personal systems.',
    wordCount: 215,
    relationships: {
      'Has': [
        '[[on-writing-well|On Writing Well]]',
        '[[engineering-leadership-101|Engineering Leadership 101]]',
        '[[ai-agents-primer|AI Agents Primer]]',
      ],
      'Topics': ['[[growth]]', '[[writing]]'],
      'Related to': ['[[growth]]'],
      'Type': ['[[responsibility]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['on-writing-well', 'engineering-leadership-101', 'ai-agents-primer', 'growth', 'writing'],
    properties: { Priority: 'High', Rating: 5, Cadence: 'Weekly', Owner: 'Srinivas Pendela' },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/manage-sponsorships.md',
    filename: 'manage-sponsorships.md',
    title: 'Manage Sponsorships',
    isA: 'Responsibility',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: 'Active',
    archived: false,
    modifiedAt: now - 7200,
    createdAt: now - 86400 * 150,
    fileSize: 890,
    snippet: 'Revenue stream from newsletter sponsorships. Karthik Reddy handles day-to-day operations.',
    wordCount: 180,
    relationships: {
      'Owner': ['[[karthik-reddy|Karthik Reddy]]'],
      'Type': ['[[responsibility]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['karthik-reddy'],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/write-weekly-essays.md',
    filename: 'write-weekly-essays.md',
    title: 'Write Weekly Essays',
    isA: 'Procedure',
    aliases: [],
    belongsTo: ['[[grow-newsletter]]'],
    relatedTo: [],
    status: 'Paused',
    archived: false,
    modifiedAt: now - 86400,
    createdAt: now - 86400 * 120,
    fileSize: 512,
    snippet: 'Monday: Pick topic, outline Tuesday: First draft Wednesday: Edit and polish Thursday: Schedule for Tuesday send',
    wordCount: 95,
    relationships: {
      'Belongs to': ['[[grow-newsletter]]'],
      'Type': ['[[procedure]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['grow-newsletter'],
    properties: { Owner: 'Srinivas Pendela', Cadence: 'Weekly' },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/run-sponsorships.md',
    filename: 'run-sponsorships.md',
    title: 'Run Sponsorships',
    isA: 'Procedure',
    aliases: [],
    belongsTo: ['[[manage-sponsorships]]'],
    relatedTo: [],
    status: 'Done',
    archived: false,
    modifiedAt: now - 86400 * 2,
    createdAt: now - 86400 * 100,
    fileSize: 640,
    snippet: 'Review pipeline in CRM Follow up with pending proposals Schedule confirmed sponsors Send performance reports to completed sponsors',
    wordCount: 128,
    relationships: {
      'Belongs to': ['[[manage-sponsorships]]'],
      'Type': ['[[procedure]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['manage-sponsorships'],
    properties: { Owner: 'Karthik Reddy', Cadence: 'Weekly' },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/stock-screener.md',
    filename: 'stock-screener.md',
    title: 'Stock Screener — EMA200 Wick Bounce',
    isA: 'Experiment',
    aliases: ['Trading Screener'],
    belongsTo: [],
    relatedTo: ['[[trading]]', '[[algorithmic-trading]]'],
    status: 'Paused',
    archived: false,
    modifiedAt: now - 86400,
    createdAt: now - 86400 * 45,
    fileSize: 3200,
    snippet: 'Stocks that wick below the 200-day EMA and close above it show a statistically significant bounce in the following 5-10 days.',
    wordCount: 520,
    relationships: {
      'Related to': ['[[trading]]', '[[algorithmic-trading]]'],
      'Has Data': ['[[ema200-backtest-results]]'],
      'Type': ['[[experiment]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['trading', 'algorithmic-trading', 'ema200-backtest-results'],
    properties: { Priority: 'Low', 'Due date': '2026-03-01', Owner: 'Srinivas Pendela' },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/facebook-ads-strategy.md',
    filename: 'facebook-ads-strategy.md',
    title: 'Facebook Ads Strategy',
    isA: 'Note',
    aliases: [],
    belongsTo: ['[[26q1-grimoire-app]]'],
    relatedTo: ['[[growth]]', '[[ads]]'],
    status: null,
    archived: false,
    modifiedAt: now - 3600 * 5,
    createdAt: now - 86400 * 30,
    fileSize: 847,
    snippet: 'Lookalike audiences from newsletter subscribers convert 3x better than interest-based targeting Video ads outperform static images by 40% on engagement',
    wordCount: 267,
    relationships: {
      'Belongs to': ['[[26q1-grimoire-app]]'],
      'Related to': ['[[growth]]', '[[ads]]'],
      'Type': ['[[note]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['26q1-grimoire-app', 'growth', 'ads'],
    properties: { Priority: 'Medium', Rating: 4 },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/budget-allocation.md',
    filename: 'budget-allocation.md',
    title: 'Budget Allocation',
    isA: 'Note',
    aliases: [],
    belongsTo: ['[[26q1-grimoire-app]]'],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400,
    createdAt: now - 86400 * 20,
    fileSize: 560,
    snippet: 'Under budget on ads due to improved targeting efficiency Consider reallocating savings to content production',
    wordCount: 150,
    relationships: {
      'Belongs to': ['[[26q1-grimoire-app]]'],
      'Type': ['[[note]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['26q1-grimoire-app'],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/karthik-reddy.md',
    filename: 'karthik-reddy.md',
    title: 'Karthik Reddy',
    isA: 'Person',
    aliases: ['Karthik'],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 7,
    createdAt: now - 86400 * 200,
    fileSize: 320,
    snippet: 'Sponsorship manager — handles all sponsor relationships, proposals, and reporting.',
    wordCount: 88,
    relationships: {
      'Type': ['[[person]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: { Company: 'Acme Corp', Role: 'Engineering Lead' },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/meera-krishnan.md',
    filename: 'meera-krishnan.md',
    title: 'Meera Krishnan',
    isA: 'Person',
    aliases: ['Maria'],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 3,
    createdAt: now - 86400 * 150,
    fileSize: 280,
    snippet: 'Product designer — leads UX research and design sprints for the app.',
    wordCount: 120,
    relationships: {
      'Type': ['[[person]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: { Company: 'TechStart', Role: 'Product Manager' },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/arun-kumar.md',
    filename: 'arun-kumar.md',
    title: 'Arun Kumar',
    isA: 'Person',
    aliases: ['Arun'],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 5,
    createdAt: now - 86400 * 120,
    fileSize: 240,
    snippet: 'Frontend engineer — focuses on React performance and accessibility.',
    wordCount: 95,
    relationships: {
      'Type': ['[[person]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/deepti-singh.md',
    filename: 'deepti-singh.md',
    title: 'Deepti Singh',
    isA: 'Person',
    aliases: ['Elena'],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 10,
    createdAt: now - 86400 * 90,
    fileSize: 200,
    snippet: 'Content strategist — plans newsletter topics and manages the editorial calendar.',
    wordCount: 75,
    relationships: {
      'Type': ['[[person]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/2026-02-14-grimoire-app-kickoff.md',
    filename: '2026-02-14-grimoire-app-kickoff.md',
    title: 'Grimoire App Design Session',
    isA: 'Event',
    aliases: [],
    belongsTo: [],
    relatedTo: ['[[26q1-grimoire-app]]', '[[karthik-reddy]]'],
    status: null,
    archived: false,
    modifiedAt: now - 3600 * 2,
    createdAt: now - 86400 * 7,
    fileSize: 1200,
    snippet: 'Agreed on four-panel layout inspired by Bear Notes CodeMirror 6 for the editor — live preview is critical MVP by end of Q1.',
    wordCount: 310,
    relationships: {
      'Related to': ['[[26q1-grimoire-app]]', '[[karthik-reddy]]'],
      'Type': ['[[event]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['26q1-grimoire-app', 'karthik-reddy'],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/software-development.md',
    filename: 'software-development.md',
    title: 'Software Development',
    isA: 'Topic',
    aliases: ['Dev', 'Coding'],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 30,
    createdAt: now - 86400 * 365,
    fileSize: 256,
    snippet: 'A broad topic covering everything from frontend to systems programming.',
    wordCount: 45,
    relationships: {
      'Notes': ['[[facebook-ads-strategy]]', '[[budget-allocation]]'],
      'Type': ['[[topic]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/trading.md',
    filename: 'trading.md',
    title: 'Trading',
    isA: 'Topic',
    aliases: ['Algorithmic Trading'],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 14,
    createdAt: now - 86400 * 300,
    fileSize: 180,
    snippet: 'Technical analysis (EMA, RSI, volume patterns) Algorithmic screening and alerts Risk management and position sizing',
    wordCount: 60,
    relationships: {
      'Notes': ['[[stock-screener]]'],
      'Type': ['[[topic]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/on-writing-well.md',
    filename: 'on-writing-well.md',
    title: 'On Writing Well',
    isA: 'Essay',
    aliases: [],
    belongsTo: ['[[grow-newsletter]]'],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 3,
    createdAt: now - 86400 * 14,
    fileSize: 4200,
    snippet: 'Good writing is lean and confident. Every sentence should serve a purpose.',
    wordCount: 180,
    relationships: {
      'Belongs to': ['[[grow-newsletter]]'],
      'Type': ['[[essay]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['grow-newsletter'],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/engineering-leadership-101.md',
    filename: 'engineering-leadership-101.md',
    title: 'Engineering Leadership 101',
    isA: 'Essay',
    aliases: [],
    belongsTo: ['[[grow-newsletter]]'],
    relatedTo: ['[[software-development]]'],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 7,
    createdAt: now - 86400 * 30,
    fileSize: 3800,
    snippet: 'The transition from IC to manager is the hardest career shift in engineering.',
    wordCount: 640,
    relationships: {
      'Belongs to': ['[[grow-newsletter]]'],
      'Related to': ['[[software-development]]'],
      'Type': ['[[essay]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['grow-newsletter', 'software-development'],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/ai-agents-primer.md',
    filename: 'ai-agents-primer.md',
    title: 'AI Agents Primer',
    isA: 'Essay',
    aliases: [],
    belongsTo: ['[[grow-newsletter]]'],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 10,
    createdAt: now - 86400 * 21,
    fileSize: 5100,
    snippet: 'AI agents are autonomous systems that can plan, execute, and adapt to achieve goals.',
    wordCount: 410,
    relationships: {
      'Belongs to': ['[[grow-newsletter]]'],
      'Type': ['[[essay]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: ['grow-newsletter'],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  // --- Type documents ---
  {
    path: '/Users/srinivas/Grimoire/project.md',
    filename: 'project.md',
    title: 'Project',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 320,
    snippet: 'A time-bound initiative that advances a Responsibility. Projects have a clear start, end, and deliverables.',
    wordCount: 280,
    relationships: {},
    icon: null,
    color: null,
    order: 0,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/responsibility.md',
    filename: 'responsibility.md',
    title: 'Responsibility',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 280,
    snippet: 'An ongoing area of ownership — something you\'re accountable for indefinitely.',
    wordCount: 50,
    relationships: {},
    icon: null,
    color: null,
    order: 1,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/procedure.md',
    filename: 'procedure.md',
    title: 'Procedure',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 310,
    snippet: 'A recurring process tied to a Responsibility. Procedures have a cadence and describe how to do something.',
    wordCount: 45,
    relationships: {},
    icon: null,
    color: null,
    order: 2,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/experiment.md',
    filename: 'experiment.md',
    title: 'Experiment',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 290,
    snippet: 'A hypothesis-driven investigation with a clear test and measurable outcome.',
    wordCount: 55,
    relationships: {},
    icon: null,
    color: null,
    order: 3,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: false,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/person.md',
    filename: 'person.md',
    title: 'Person',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 200,
    snippet: 'A person you interact with — team members, collaborators, contacts.',
    wordCount: 40,
    relationships: {},
    icon: null,
    color: null,
    order: 4,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/event.md',
    filename: 'event.md',
    title: 'Event',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 180,
    snippet: 'A point-in-time occurrence — meetings, launches, milestones.',
    wordCount: 35,
    relationships: {},
    icon: null,
    color: null,
    order: 5,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/topic.md',
    filename: 'topic.md',
    title: 'Topic',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 170,
    snippet: 'A subject area for categorization. Topics group related notes, projects, and resources by theme.',
    wordCount: 30,
    relationships: {},
    icon: null,
    color: null,
    order: 6,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/essay.md',
    filename: 'essay.md',
    title: 'Essay',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 200,
    snippet: 'A published piece of writing — newsletter essays, blog posts, articles.',
    wordCount: 50,
    relationships: {},
    icon: null,
    color: null,
    order: 7,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/note.md',
    filename: 'note.md',
    title: 'Note',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 365,
    fileSize: 190,
    snippet: 'A general-purpose document — research notes, meeting notes, strategy docs.',
    wordCount: 60,
    relationships: {},
    icon: null,
    color: null,
    order: 8,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  // --- Custom type documents ---
  {
    path: '/Users/srinivas/Grimoire/config.md',
    filename: 'config.md',
    title: 'Config',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 30,
    createdAt: now - 86400 * 365,
    fileSize: 300,
    snippet: 'Vault configuration files. These control how AI agents, tools, and other integrations interact with this vault.',
    wordCount: 25,
    relationships: {},
    icon: 'gear-six',
    color: 'gray',
    order: 90,
    sidebarLabel: 'Config',
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/recipe.md',
    filename: 'recipe.md',
    title: 'Recipe',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 30,
    createdAt: now - 86400 * 365,
    fileSize: 250,
    snippet: 'A recipe for cooking or baking. Recipes have ingredients, steps, and serving info.',
    wordCount: 45,
    relationships: {},
    icon: 'cooking-pot',
    color: 'orange',
    order: 9,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/book.md',
    filename: 'book.md',
    title: 'Book',
    isA: 'Type',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 30,
    createdAt: now - 86400 * 365,
    fileSize: 220,
    snippet: 'A book you\'re reading or have read. Track reading progress, notes, and key takeaways.',
    wordCount: 190,
    relationships: {},
    icon: 'book-open',
    color: 'green',
    order: 10,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  // --- Instances of custom types ---
  {
    path: '/Users/srinivas/Grimoire/config/agents.md',
    filename: 'agents.md',
    title: 'Agent Instructions',
    isA: 'Config',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 5,
    createdAt: now - 86400 * 30,
    fileSize: 1200,
    snippet: 'Vault instructions for AI agents. Defines how tools and integrations interact with this vault.',
    wordCount: 200,
    relationships: {
      'Type': ['[[config]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/pasta-carbonara.md',
    filename: 'pasta-carbonara.md',
    title: 'Pasta Carbonara',
    isA: 'Recipe',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 5,
    createdAt: now - 86400 * 10,
    fileSize: 420,
    snippet: 'Classic Roman pasta dish with eggs, pecorino, guanciale, and black pepper.',
    wordCount: 310,
    relationships: {
      'Type': ['[[recipe]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: { Difficulty: 'Easy', 'Prep time': '30 min', Servings: 4 },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/designing-data-intensive-applications.md',
    filename: 'designing-data-intensive-applications.md',
    title: 'Designing Data-Intensive Applications',
    isA: 'Book',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 14,
    createdAt: now - 86400 * 60,
    fileSize: 380,
    snippet: 'Essential reading for anyone building distributed systems. Covers replication, partitioning, transactions.',
    wordCount: 100,
    relationships: {
      'Type': ['[[book]]'],
    },
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: { Author: 'Martin Kleppmann', Rating: 5, 'Year published': 2017 },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  // --- Archived entries ---
  {
    path: '/Users/srinivas/Grimoire/25q3-website-redesign.md',
    filename: '25q3-website-redesign.md',
    title: 'Website Redesign',
    isA: 'Project',
    aliases: [],
    belongsTo: ['[[q3-2025]]'],
    relatedTo: [],
    status: 'Done',
    archived: true,
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: { Owner: 'Srinivas Pendela' },
    modifiedAt: now - 86400 * 120,
    createdAt: now - 86400 * 200,
    fileSize: 680,
    snippet: 'Completed redesign of the company website. Migrated from WordPress to Next.js with improved performance and SEO.',
    wordCount: 342,
    relationships: {
      'Belongs to': ['[[q3-2025]]'],
      'Type': ['[[project]]'],
    },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/twitter-thread-experiment.md',
    filename: 'twitter-thread-experiment.md',
    title: 'Twitter Thread Growth Experiment',
    isA: 'Experiment',
    aliases: [],
    belongsTo: [],
    relatedTo: ['[[grow-newsletter]]'],
    status: 'Done',
    archived: true,
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: { Owner: 'Srinivas Pendela' },
    modifiedAt: now - 86400 * 90,
    createdAt: now - 86400 * 150,
    fileSize: 520,
    snippet: 'Publishing 3 Twitter threads per week instead of 1 will increase newsletter signups by 50%. Result: only 12% increase.',
    wordCount: 215,
    relationships: {
      'Related to': ['[[grow-newsletter]]'],
      'Type': ['[[experiment]]'],
    },
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  // --- Refactoring entries for exact-match search testing ---
  {
    path: '/Users/srinivas/Grimoire/refactoring.md',
    filename: 'refactoring.md',
    title: 'Refactoring',
    isA: 'Area',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: 'Active',
    archived: false,
    modifiedAt: now - 86400 * 30,
    createdAt: now - 86400 * 365,
    fileSize: 1200,
    snippet: 'Area note covering refactoring practices and principles.',
    wordCount: 180,
    relationships: {},
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/refactoring-ideas.md',
    filename: 'refactoring-ideas.md',
    title: 'Refactoring Ideas',
    isA: 'Note',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 5,
    createdAt: now - 86400 * 60,
    fileSize: 800,
    snippet: 'Ideas for refactoring the codebase.',
    wordCount: 120,
    relationships: {},
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/refactoring-key-ideas.md',
    filename: 'refactoring-key-ideas.md',
    title: 'Refactoring Key Ideas',
    isA: 'Note',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 10,
    createdAt: now - 86400 * 90,
    fileSize: 600,
    snippet: 'Key ideas from the refactoring book.',
    wordCount: 95,
    relationships: {},
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
  {
    path: '/Users/srinivas/Grimoire/refactoring-patterns.md',
    filename: 'refactoring-patterns.md',
    title: 'Refactoring Patterns',
    isA: 'Note',
    aliases: [],
    belongsTo: [],
    relatedTo: [],
    status: null,
    archived: false,
    modifiedAt: now - 86400 * 15,
    createdAt: now - 86400 * 120,
    fileSize: 950,
    snippet: 'Common refactoring patterns and when to apply them.',
    wordCount: 150,
    relationships: {},
    icon: null,
    color: null,
    order: null,
    sidebarLabel: null,
    template: null, sort: null, view: null, visible: null,
    outgoingLinks: [],
    properties: {},
    organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
  },
]

// --- Bulk entry generator for large vault testing ---

const BULK_TYPES = ['Note', 'Project', 'Experiment', 'Responsibility', 'Procedure', 'Person', 'Event', 'Essay', 'Topic']
const BULK_ADJECTIVES = ['Quick', 'Advanced', 'Daily', 'Weekly', 'Annual', 'Draft', 'Final', 'Revised', 'Archived', 'New']
const BULK_NOUNS = ['Meeting', 'Strategy', 'Review', 'Plan', 'Analysis', 'Summary', 'Report', 'Guide', 'Checklist', 'Template', 'Framework', 'Workflow', 'Retrospective', 'Brainstorm', 'Proposal']
const BULK_SNIPPETS = [
  'Key findings from the latest analysis session.',
  'Notes on process improvements and next steps.',
  'Summary of decisions made during the review.',
  'Action items and follow-ups from discussion.',
  'Draft outline for upcoming deliverable.',
  'Reference material for the ongoing initiative.',
  'Tracking progress on quarterly objectives.',
  'Comparison of different approaches considered.',
]

function generateBulkEntries(count: number): VaultEntry[] {
  const entries: VaultEntry[] = []
  for (let i = 0; i < count; i++) {
    const type = BULK_TYPES[i % BULK_TYPES.length]
    const adj = BULK_ADJECTIVES[i % BULK_ADJECTIVES.length]
    const noun = BULK_NOUNS[i % BULK_NOUNS.length]
    const title = `${adj} ${noun} ${i + 1}`
    const slug = title.toLowerCase().replace(/\s+/g, '-')
    entries.push({
      path: `/Users/srinivas/Grimoire/${slug}.md`,
      filename: `${slug}.md`,
      title,
      isA: type,
      aliases: [],
      belongsTo: [],
      relatedTo: [],
      status: i % 4 === 0 ? 'Active' : i % 4 === 1 ? 'Paused' : i % 4 === 2 ? 'Done' : null,
      archived: false,
      modifiedAt: now - i * 600,
      createdAt: now - 86400 * 90 - i * 3600,
      fileSize: 500 + (i % 2000),
      snippet: BULK_SNIPPETS[i % BULK_SNIPPETS.length],
      wordCount: 50 + (i % 200),
      relationships: {},
      icon: null,
      color: null,
      order: null,
      outgoingLinks: Array.from({ length: i % 8 }, (_j, j) => `link-target-${(i + j) % 50}`),
      sidebarLabel: null,
      template: null, sort: null, view: null, visible: null,
      properties: {},
      organized: false, favorite: false, favoriteIndex: null, listPropertiesDisplay: [], hasH1: false,
    })
  }
  return entries
}

const configuredBulkCount = Number(import.meta.env.VITE_GRIMOIRE_MOCK_BULK_COUNT ?? 0)

// Keep browser dev mode responsive by default; enable large-vault stress data
// explicitly with VITE_GRIMOIRE_MOCK_BULK_COUNT=9000.
if (Number.isFinite(configuredBulkCount) && configuredBulkCount > 0) {
  MOCK_ENTRIES.push(...generateBulkEntries(configuredBulkCount))
}
