import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('dashboard theme CSS', () => {
  const appCss = readFileSync(`${process.cwd()}/src/App.css`, 'utf8')
  const coherenceCss = readFileSync(`${process.cwd()}/src/theme-coherence.css`, 'utf8')
  const surfaceCoherenceCss = readFileSync(`${process.cwd()}/src/theme-surface-coherence.css`, 'utf8')
  const dashboardLayoutCss = readFileSync(`${process.cwd()}/src/components/dashboard/VaultDashboardLayout.css`, 'utf8')
  const dashboardCss = readFileSync(`${process.cwd()}/src/components/dashboard/VaultDashboard.css`, 'utf8')
  const dreamForgeCss = readFileSync(`${process.cwd()}/src/components/dashboard/DreamForgePanel.css`, 'utf8')
  const todayRunwayCss = readFileSync(`${process.cwd()}/src/components/dashboard/DashboardTodayRunway.css`, 'utf8')

  it('routes dashboard and Dream Forge surfaces through theme-owned materials', () => {
    expect(appCss).toContain('background: var(--grimoire-dashboard-material')
    expect(coherenceCss).toContain('--grimoire-dashboard-material')
    expect(coherenceCss).toContain('--grimoire-private-local-material')
    expect(surfaceCoherenceCss).toContain('--grimoire-rail-material')
    expect(surfaceCoherenceCss).toContain('.vault-dashboard__flow')
    expect(surfaceCoherenceCss).toContain('.vault-dashboard__ask-preview')
    expect(todayRunwayCss).toContain('background: var(--grimoire-rail-material')
    expect(todayRunwayCss).toContain('background: var(--grimoire-rail-card-material')
    expect(todayRunwayCss).toContain('box-shadow: var(--grimoire-surface-shadow')
    expect(coherenceCss).toContain('--grimoire-private-local-border')
    expect(coherenceCss).toContain('--grimoire-private-local-glow')
    expect(dreamForgeCss).toContain('background: var(--grimoire-private-local-material')
    expect(dreamForgeCss).toContain('border-color: var(--grimoire-private-local-border')
    expect(dreamForgeCss).toContain('box-shadow: var(--grimoire-private-local-glow')
    expect(dreamForgeCss).toContain('var(--grimoire-private-chip-bg')
    expect(dreamForgeCss).toContain('var(--grimoire-private-chip-fg')
    expect(dreamForgeCss).toContain('.vault-dashboard__dream-contract')
    expect(dreamForgeCss).toContain('.vault-dashboard__dream-timeline')
  })

  it('keeps Dream Forge motion finite and reduced-motion safe', () => {
    expect(dreamForgeCss).toContain('@media (prefers-reduced-motion: no-preference)')
    expect(dreamForgeCss).toContain('animation: grimoire-dream-signal-arrive')
    expect(dreamForgeCss).not.toMatch(/\banimation:[^;{}]*\binfinite\b/u)
    expect(todayRunwayCss).toContain('@media (prefers-reduced-motion: no-preference)')
    expect(todayRunwayCss).toContain('animation: grimoire-flow-next-arrive')
    expect(todayRunwayCss).not.toMatch(/\banimation:[^;{}]*\binfinite\b/u)
  })

  it('routes Time Loom through shared signal and private-local materials', () => {
    expect(dashboardCss).toContain('.vault-dashboard__daily-thread')
    expect(dashboardCss).toContain('.vault-dashboard__daily-thread-lane[data-state="private"]')
    expect(dashboardCss).toContain('.vault-dashboard__time-map')
    expect(dashboardCss).toContain('.vault-dashboard__time-graph')
    expect(dashboardCss).toContain('.vault-dashboard__time-graph-node[data-privacy="held-local"]')
    expect(dashboardCss).toContain('background: var(--grimoire-signal-bg')
    expect(dashboardCss).toContain('var(--grimoire-private-chip-bg')
    expect(dashboardCss).toContain('animation: grimoire-time-node-arrive')
  })

  it('keeps Daily Thread and Time Loom responsive inside resized panes', () => {
    expect(dashboardLayoutCss).toContain('--vault-dashboard-content-max: 1480px')
    expect(dashboardLayoutCss).toContain('container-name: vault-dashboard')
    expect(dashboardLayoutCss).toContain('container-type: inline-size')
    expect(dashboardLayoutCss).toContain('max-width: var(--vault-dashboard-content-max)')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__markdown-tools')
    expect(dashboardLayoutCss).toContain('line-height: var(--editor-line-height, 1.44)')
    expect(dashboardLayoutCss).toContain('grid-template-columns: minmax(0, 1.35fr) minmax(0, 0.8fr)')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__grid > *')
    expect(dashboardLayoutCss).toContain('@container vault-dashboard (max-width: 860px)')
    expect(dashboardLayoutCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 130px), 1fr))')
    expect(dashboardLayoutCss).not.toContain('grid-template-columns: repeat(2, minmax(130px, 1fr))')
    expect(todayRunwayCss).toContain('container-type: inline-size')
    expect(todayRunwayCss).toContain('@container (max-width: 840px)')
    expect(todayRunwayCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 128px), 1fr))')
    expect(todayRunwayCss).toContain('margin-top: 10px')
    expect(dashboardCss).toContain('container-name: time-loom')
    expect(dashboardCss).toContain('@container time-loom (max-width: 720px)')
    expect(dashboardCss).toContain('@container vault-dashboard (max-width: 420px)')
    expect(dashboardCss).not.toContain('@media (max-width: 720px)')
    expect(dashboardCss).not.toContain('@media (max-width: 420px)')
    expect(dashboardCss).toContain('flex-wrap: wrap')
    expect(dashboardCss).toContain('grid-column: 1 / -1')
    expect(dashboardCss).toContain('font-family: var(--grimoire-ui-font-family)')
    expect(dashboardCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 96px), 1fr))')
    expect(dashboardCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 112px), 1fr))')
    expect(dashboardCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 150px), 1fr))')
    expect(dreamForgeCss).toContain('container-name: dream-forge')
    expect(dreamForgeCss).toContain('@container dream-forge (max-width: 560px)')
    expect(dreamForgeCss).not.toContain('@media (max-width: 560px)')
  })
})
