import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('dashboard theme CSS', () => {
  const appCss = readFileSync(`${process.cwd()}/src/App.css`, 'utf8')
  const coherenceCss = readFileSync(`${process.cwd()}/src/theme-coherence.css`, 'utf8')
  const surfaceCoherenceCss = readFileSync(`${process.cwd()}/src/theme-surface-coherence.css`, 'utf8')
  const dashboardLayoutCss = readFileSync(`${process.cwd()}/src/components/dashboard/VaultDashboardLayout.css`, 'utf8')
  const dashboardHeroCss = readFileSync(`${process.cwd()}/src/components/dashboard/DashboardHero.css`, 'utf8')
  const dashboardStatRowCss = readFileSync(`${process.cwd()}/src/components/dashboard/DashboardStatRow.css`, 'utf8')
  const dashboardResponsiveCss = readFileSync(`${process.cwd()}/src/components/dashboard/VaultDashboardResponsive.css`, 'utf8')
  const dashboardCss = readFileSync(`${process.cwd()}/src/components/dashboard/VaultDashboard.css`, 'utf8')
  const dreamForgeCss = readFileSync(`${process.cwd()}/src/components/dashboard/DreamForgePanel.css`, 'utf8')
  const todayRunwayCss = readFileSync(`${process.cwd()}/src/components/dashboard/DashboardTodayRunway.css`, 'utf8')
  const todayRunwayMotionCss = readFileSync(`${process.cwd()}/src/components/dashboard/DashboardTodayRunwayMotion.css`, 'utf8')
  const todayRunwayResponsiveCss = readFileSync(`${process.cwd()}/src/components/dashboard/DashboardTodayRunwayResponsive.css`, 'utf8')

  it('routes dashboard and Dream Review surfaces through theme-owned materials', () => {
    expect(appCss).toContain('background: var(--grimoire-dashboard-material')
    expect(coherenceCss).toContain('--grimoire-dashboard-material')
    expect(coherenceCss).toContain('--grimoire-private-local-material')
    expect(surfaceCoherenceCss).toContain('--grimoire-rail-material')
    expect(surfaceCoherenceCss).toContain('.vault-dashboard__flow')
    expect(surfaceCoherenceCss).toContain('.vault-dashboard__ask-preview')
    expect(todayRunwayCss).toContain('.vault-dashboard__today-runway .vault-dashboard__flow')
    expect(todayRunwayCss).toContain('background: transparent')
    expect(todayRunwayCss).toContain('box-shadow: none')
    expect(coherenceCss).toContain('--grimoire-private-local-border')
    expect(coherenceCss).toContain('--grimoire-private-local-glow')
    expect(dreamForgeCss).toContain('background: var(--grimoire-private-local-material')
    expect(dreamForgeCss).toContain('border-color: var(--grimoire-private-local-border')
    expect(dreamForgeCss).toContain('box-shadow: var(--grimoire-private-local-glow')
    expect(dreamForgeCss).toContain('var(--grimoire-private-chip-bg')
    expect(dreamForgeCss).toContain('var(--grimoire-private-chip-fg')
    expect(dreamForgeCss).toContain('.vault-dashboard__dream-contract')
    expect(dreamForgeCss).toContain('.vault-dashboard__dream-timeline')
  })

  it('keeps Dream Review motion finite and reduced-motion safe', () => {
    expect(dreamForgeCss).toContain('@media (prefers-reduced-motion: no-preference)')
    expect(dreamForgeCss).toContain('animation: grimoire-dream-signal-arrive')
    expect(dreamForgeCss).not.toMatch(/\banimation:[^;{}]*\binfinite\b/u)
    expect(todayRunwayMotionCss).toContain('@media (prefers-reduced-motion: no-preference)')
    expect(todayRunwayMotionCss).toContain('animation: grimoire-flow-next-arrive')
    expect(todayRunwayMotionCss).toContain('animation: grimoire-flow-next-arrive 420ms')
    expect(todayRunwayMotionCss).not.toContain('grimoire-assistant-brief-arrive')
    expect(todayRunwayMotionCss).toContain('transform: scale(1.025)')
    expect(todayRunwayMotionCss).toContain('@media (prefers-reduced-motion: reduce)')
    expect(todayRunwayMotionCss).toContain('transition-duration: 0ms')
    expect(todayRunwayMotionCss).not.toContain('var(--motion-duration-cinematic')
    expect(todayRunwayMotionCss).not.toContain('transform: scale(1.04)')
    expect(todayRunwayMotionCss).not.toContain('transform: scale(1.18)')
    expect(todayRunwayMotionCss).not.toMatch(/\banimation:[^;{}]*\binfinite\b/u)
  })

  it('routes the trail through shared signal and private-local materials', () => {
    expect(dashboardCss).toContain('.vault-dashboard__daily-thread')
    expect(dashboardCss).toContain('.vault-dashboard__daily-thread-lane[data-state="private"]')
    expect(dashboardCss).toContain('.vault-dashboard__time-map')
    expect(dashboardCss).toContain('.vault-dashboard__time-graph')
    expect(dashboardCss).toContain('.vault-dashboard__time-graph-node[data-privacy="held-local"]')
    expect(dashboardCss).toContain('background: var(--grimoire-signal-bg')
    expect(dashboardCss).toContain('var(--grimoire-private-chip-bg')
    expect(dashboardCss).toContain('animation: grimoire-time-node-arrive')
  })

  it('keeps Daily Thread and the trail responsive inside resized panes', () => {
    expect(dashboardLayoutCss).toContain('--vault-dashboard-content-max: 1480px')
    expect(dashboardLayoutCss).toContain('container-name: vault-dashboard')
    expect(dashboardLayoutCss).toContain('container-type: inline-size')
    expect(dashboardLayoutCss).toContain('max-width: var(--vault-dashboard-content-max)')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__markdown-tools')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__capture-form:not(:focus-within):not([data-has-input="true"]) .vault-dashboard__markdown-tools')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__capture-form:not(:focus-within):not([data-has-input="true"]) .vault-dashboard__template-picker')
    // Footer chips + capture button stay visible (mockup-caliber capture card), not collapsed with the meta tools.
    expect(dashboardLayoutCss).not.toContain('.vault-dashboard__capture-form:not(:focus-within):not([data-has-input="true"]) .vault-dashboard__capture-kinds')
    expect(dashboardLayoutCss).toContain('line-height: var(--editor-line-height, 1.44)')
    expect(dashboardLayoutCss).toContain('grid-template-columns: minmax(0, 1.35fr) minmax(0, 0.8fr)')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__grid > *')
    expect(dashboardResponsiveCss).toContain('@container vault-dashboard (max-width: 860px)')
    expect(dashboardLayoutCss).not.toContain('order: -1')
    expect(dashboardResponsiveCss).toContain('@container vault-dashboard (max-width: 520px)')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__panel--capture')
    expect(dashboardResponsiveCss).toContain('min-height: 154px')
    expect(dashboardLayoutCss).toContain('width: 36px')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__capture-submit')
    expect(dashboardResponsiveCss).toContain('min-height: 44px')
    expect(dashboardResponsiveCss).toContain('width: 44px')
    expect(dashboardResponsiveCss).not.toContain('min-height: 36px')
    expect(dashboardResponsiveCss).not.toContain('min-height: 32px')
    expect(dashboardResponsiveCss).not.toContain('min-height: 22px')
    expect(dashboardLayoutCss).not.toContain('grid-template-columns: repeat(2, minmax(130px, 1fr))')
    expect(todayRunwayCss).toContain('container-type: inline-size')
    expect(todayRunwayResponsiveCss).toContain('@container (max-width: 840px)')
    expect(todayRunwayResponsiveCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 128px), 1fr))')
    expect(todayRunwayCss).toContain('margin-top: 10px')
    expect(dashboardCss).toContain('container-name: time-loom')
    expect(dashboardCss).toContain('@container time-loom (max-width: 720px)')
    expect(dashboardCss).toContain('@container vault-dashboard (max-width: 420px)')
    expect(dashboardCss).not.toContain('@media (max-width: 720px)')
    expect(dashboardCss).not.toContain('@media (max-width: 420px)')
    expect(dashboardCss).toContain('flex-wrap: wrap')
    expect(dashboardCss).toContain('grid-column: 1 / -1')
    expect(dashboardCss).toContain('font-family: var(--grimoire-ui-font-family)')
    expect(dashboardCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 96px), 1fr))')
    expect(dashboardCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 112px), 1fr))')
    expect(dashboardCss).toContain('grid-template-columns: repeat(auto-fit, minmax(min(100%, 150px), 1fr))')
    expect(dreamForgeCss).toContain('container-name: dream-forge')
    expect(dreamForgeCss).toContain('@container dream-forge (max-width: 560px)')
    expect(dreamForgeCss).not.toContain('@media (max-width: 560px)')
  })

  it('keeps dashboard chrome native while giving titles a notebook voice', () => {
    expect(dashboardLayoutCss).toContain("--vault-dashboard-chrome-font: -apple-system, BlinkMacSystemFont, 'SF Pro Text'")
    expect(dashboardLayoutCss).toContain("--vault-dashboard-title-font: var(--grimoire-display-font-family")
    expect(dashboardLayoutCss).toContain('font-family: var(--vault-dashboard-chrome-font)')
    expect(dashboardLayoutCss).toContain('font-family: var(--vault-dashboard-title-font)')
    // Notebook voice lives in the hero display title (sentence-case, tested in
    // the hero test). Small section-label eyebrows use uppercase to match the
    // mockups, so the old blanket no-uppercase / fixed-weight guards are dropped.
    expect(dashboardLayoutCss).toContain('var(--grimoire-native-card-material')
    expect(dashboardLayoutCss).toContain('var(--grimoire-native-card-border')
    expect(dashboardLayoutCss).toContain('var(--grimoire-native-card-shadow')
  })

  it('gives the hero band a clean-sans display title over warm card material', () => {
    expect(dashboardHeroCss).toContain('.dashboard-hero')
    expect(dashboardHeroCss).toContain('grid-column: 1 / -1')
    expect(dashboardHeroCss).toContain('font-family: var(--grimoire-display-font-family)')
    expect(dashboardHeroCss).toContain('font-size: clamp(30px, 4vw, 44px)')
    expect(dashboardHeroCss).toContain('line-height: 1.05')
    expect(dashboardHeroCss).toContain('color: var(--text-heading)')
    expect(dashboardHeroCss).toContain('.dashboard-hero__tagline')
    expect(dashboardHeroCss).toContain('background: var(--grimoire-card-material')
    expect(dashboardHeroCss).toContain('.dashboard-hero__aurora')
    expect(dashboardHeroCss).toContain('color-mix(in srgb, var(--primary)')
    expect(dashboardHeroCss).toContain('pointer-events: none')
    expect(dashboardHeroCss).not.toContain('text-transform: uppercase')
    expect(dashboardHeroCss).not.toMatch(/font-family:[^;]*serif/u)
  })

  it('promotes the stat row to a four-up big-number band on aurora tokens', () => {
    expect(dashboardStatRowCss).toContain('.dashboard-stat-row')
    expect(dashboardStatRowCss).toContain('grid-column: 1 / -1')
    expect(dashboardStatRowCss).toContain('grid-template-columns: repeat(4, minmax(0, 1fr))')
    expect(dashboardStatRowCss).toContain('font-size: var(--font-size-stat, 42px)')
    expect(dashboardStatRowCss).toContain('color: var(--text-primary)')
    expect(dashboardStatRowCss).toContain('box-shadow: var(--elevation-1)')
    expect(dashboardStatRowCss).toContain('border: 1px solid var(--grimoire-hairline)')
    expect(dashboardStatRowCss).toContain('@container vault-dashboard (max-width: 720px)')
    expect(dashboardStatRowCss).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(dashboardStatRowCss).not.toContain('color: var(--primary)')
  })

  it('keeps the first notebook surface out of magic and green-shell styling', () => {
    const quickCaptureSource = readFileSync(`${process.cwd()}/src/components/dashboard/DashboardQuickCapturePanel.tsx`, 'utf8')

    expect(quickCaptureSource).toContain('PenLine')
    expect(quickCaptureSource).toContain('data-has-input')
    expect(quickCaptureSource).not.toContain('WandSparkles')
    expect(todayRunwayCss).toContain('.vault-dashboard__panel.vault-dashboard__assistant-brief')
    expect(todayRunwayCss).toContain('var(--grimoire-native-card-material')
    expect(todayRunwayCss).toContain('var(--grimoire-native-card-border')
    expect(todayRunwayCss).toContain('var(--grimoire-native-card-shadow')
    expect(todayRunwayCss).not.toContain('vault-dashboard__assistant-lines')
    expect(todayRunwayCss).not.toContain('accent-green')
    expect(coherenceCss).toContain('.vault-dashboard__panel:not(.vault-dashboard__panel--capture):not(.vault-dashboard__assistant-brief)')
    expect(dashboardLayoutCss).not.toContain('.vault-dashboard__badge--local {\n  border-color: color-mix(in srgb, var(--accent-green')
    expect(dashboardLayoutCss).not.toContain('.vault-dashboard__badges')
    expect(dashboardLayoutCss).not.toContain('.vault-dashboard__badge--')
    expect(dashboardResponsiveCss).not.toContain('.vault-dashboard__badges')
    expect(dashboardResponsiveCss).not.toContain('.vault-dashboard__badge')
    expect(dashboardLayoutCss).toContain('.vault-dashboard__new-page-button')
  })
})
