import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('sidebar artwork theme CSS', () => {
  it('styles the ambient sidebar glyph layer for live sidebars and previews', () => {
    const css = readFileSync(`${process.cwd()}/src/sidebar-artwork-themes.css`, 'utf8')

    expect(css).toContain('.app-sidebar-panel > .sidebar-artwork')
    expect(css).toContain('[data-sidebar-preset-preview] .sidebar-artwork')
    expect(css).toContain('.app-sidebar-panel .sidebar-artwork__glyph')
    expect(css).toContain('[data-sidebar-preset-preview] .sidebar-artwork__glyph')
    expect(css).toContain('@media (max-height: 760px)')
  })

  it('keeps glyph ink theme-aware through CSS variables and blend modes', () => {
    const css = readFileSync(`${process.cwd()}/src/sidebar-artwork-themes.css`, 'utf8')

    expect(css).toContain('.app-sidebar-panel,\n[data-sidebar-preset-preview] {')
    expect(css).toContain('--art-ink')
    expect(css).toContain('--art-aura')
    expect(css).toContain('--art-core')
    expect(css).toContain('--art-fill')
    expect(css).toContain('--art-gate')
    expect(css).toContain('--art-page')
    expect(css).toContain('--art-route')
    expect(css).toContain('--art-shield')
    expect(css).toContain('--art-memory')
    expect(css).toContain('--art-veda')
    expect(css).toContain('--art-shastra')
    expect(css).toContain('--art-brain')
    expect(css).toContain('--art-purana')
    expect(css).toContain('--art-rishi')
    expect(css).toContain('--art-second-brain')
    expect(css).toContain('--art-node-warm')
    expect(css).toContain('--art-presence')
    expect(css).toContain('calc(var(--sidebar-artwork-opacity, 0.28) * 2.35)')
    expect(css).toContain('--art-spark')
    expect(css).toContain('.sidebar-artwork__aurora')
    expect(css).toContain('.sidebar-artwork__core-glow')
    expect(css).toContain('.sidebar-artwork__local-dot')
    expect(css).toContain('.sidebar-artwork__orbit')
    expect(css).toContain('.sidebar-artwork__gate')
    expect(css).toContain('.sidebar-artwork__route')
    expect(css).toContain('.sidebar-artwork__ribbon')
    expect(css).toContain('.sidebar-artwork__palm-leaf')
    expect(css).toContain('.sidebar-artwork__purana-scroll')
    expect(css).toContain('.sidebar-artwork__rishi-aura')
    expect(css).toContain('.sidebar-artwork__second-brain')
    expect(css).toContain('.sidebar-artwork__brain-loop')
    expect(css).toContain('.sidebar-artwork__brain-node')
    expect(css).toContain('.sidebar-artwork__constellation')
    expect(css).toContain('.sidebar-artwork__memory-line')
    expect(css).toContain('.sidebar-artwork__root')
    expect(readFileSync(`${process.cwd()}/src/sidebar-artwork-polish.css`, 'utf8')).toContain('.sidebar-artwork__token')
    expect(css).toContain('[data-theme="dark"] .app-sidebar-panel .sidebar-artwork__glyph')
    expect(css).toContain('[data-theme-preview="dark"] .sidebar-artwork__glyph')
    expect(css).toContain('opacity: var(--art-presence)')
    expect(css).not.toContain('.app-sidebar-panel > .sidebar-artwork,\n[data-sidebar-preset-preview] .sidebar-artwork {\n  --art-accent')
  })

  it('keeps the live artwork as an ambient brand mark instead of a framed scene', () => {
    const css = readFileSync(`${process.cwd()}/src/sidebar-artwork-themes.css`, 'utf8')

    expect(css).toContain('mask-image: linear-gradient')
    expect(css).toContain('mix-blend-mode: normal')
    expect(css).not.toContain('mix-blend-mode: multiply')
    expect(css).not.toContain('mix-blend-mode: screen')
    expect(css).toContain('drop-shadow(0 14px 22px')
    expect(css).toContain('--art-presence: 0.62')
    expect(css).toContain('border: 0')
    expect(css).toContain('.sidebar-artwork__page')
    expect(css).toContain('.sidebar-artwork__glyph--vault-atlas')
    expect(css).toContain('transform: translateY(4px) scale(0.98)')
    expect(css).toContain('animation: sidebar-atlas-arrive')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    expect(css).not.toContain('.sidebar-artwork__vine')
    expect(css).not.toContain('.sidebar-artwork__leaf')
    expect(css).not.toContain('box-shadow: inset')
  })
})
