import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('sidebar artwork theme CSS', () => {
  const readText = (path: string): string => readFileSync(path, 'utf8').replace(/\r\n?/gu, '\n')

  it('styles the ambient notebook mark only inside settings previews', () => {
    const css = readText(`${process.cwd()}/src/sidebar-artwork-themes.css`)

    expect(css).toContain('[data-sidebar-preset-preview] .sidebar-artwork')
    expect(css).toContain('[data-sidebar-preset-preview] .sidebar-artwork__glyph')
    expect(css).toContain('@media (max-height: 760px)')
    expect(css).not.toContain('.app-sidebar-panel > .sidebar-artwork')
    expect(css).not.toContain('.app-sidebar-panel .sidebar-artwork__glyph')
  })

  it('keeps glyph ink theme-aware through CSS variables and blend modes', () => {
    const css = readText(`${process.cwd()}/src/sidebar-artwork-themes.css`)

    expect(css).toContain('[data-sidebar-preset-preview] {')
    expect(css).toContain('--art-ink')
    expect(css).toContain('--art-aura')
    expect(css).toContain('--art-page')
    expect(css).toContain('--art-memory')
    expect(css).toContain('--art-thread')
    expect(css).toContain('--art-context')
    expect(css).toContain('--art-presence')
    expect(css).toContain('calc(var(--sidebar-artwork-opacity, 0.18) * 1.15)')
    expect(css).toContain('--art-mark')
    expect(css).toContain('.sidebar-artwork__glyph--notebook-thread')
    expect(css).not.toContain('--art-core')
    expect(css).not.toContain('--art-gate')
    expect(css).not.toContain('--art-shield')
    expect(css).not.toContain('--art-annotation')
    expect(css).not.toContain('--art-thought')
    expect(css).not.toContain('--art-margin')
    expect(css).not.toContain('.sidebar-artwork__aurora')
    expect(css).not.toContain('.sidebar-artwork__core-glow')
    expect(css).not.toContain('.sidebar-artwork__orbit')
    expect(css).not.toContain('.sidebar-artwork__gate')
    expect(css).not.toContain('.sidebar-artwork__thought-loop')
    expect(css).not.toContain('.sidebar-artwork__root')
    expect(readText(`${process.cwd()}/src/sidebar-artwork-polish.css`)).not.toContain('.sidebar-artwork__token')
    expect(css).toContain('[data-theme-preview="dark"] .sidebar-artwork__glyph')
    expect(css).not.toContain('[data-theme="dark"] .app-sidebar-panel .sidebar-artwork__glyph')
    expect(css).toContain('opacity: var(--art-presence)')
    expect(css).not.toContain('.app-sidebar-panel > .sidebar-artwork,\n[data-sidebar-preset-preview] .sidebar-artwork {\n  --art-accent')
    expect(css).not.toContain('.sidebar-artwork__constellation')
    expect(css).not.toContain('.sidebar-artwork__route')
    expect(css).not.toContain('.sidebar-artwork__rishi')
    expect(css).not.toContain('.sidebar-artwork__palm-leaf')
    expect(css).not.toContain('.sidebar-artwork__purana-scroll')
    expect(css).not.toContain('#9bff7a')
    expect(css).not.toContain('#62f2b6')
    expect(css).not.toContain('--art-rishi')
    expect(css).not.toContain('--art-veda')
    expect(css).not.toContain('--art-shastra')
    expect(css).not.toContain('--art-purana')
    expect(css).not.toContain('--art-node')
  })

  it('keeps the preview artwork as an ambient brand mark instead of a framed scene', () => {
    const css = readText(`${process.cwd()}/src/sidebar-artwork-themes.css`)

    expect(css).toContain('mask-image: linear-gradient')
    expect(css).toContain('mix-blend-mode: normal')
    expect(css).not.toContain('mix-blend-mode: multiply')
    expect(css).not.toContain('mix-blend-mode: screen')
    expect(css).toContain('filter: none')
    expect(css).toContain('--art-presence: 0.26')
    expect(css).toContain('border: 0')
    expect(css).not.toContain('.sidebar-artwork__glyph--notebook-atlas')
    expect(css).toContain('.sidebar-artwork__glyph--notebook-thread')
    expect(css).toContain('transform: translateY(4px) scale(0.98)')
    expect(css).toContain('animation: sidebar-notebook-thread-arrive 240ms var(--motion-ease-standard')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
    expect(css).not.toContain('.sidebar-artwork__vine')
    expect(css).not.toContain('.sidebar-artwork__leaf')
    expect(css).not.toContain('box-shadow: inset')
    expect(css).not.toContain('drop-shadow(0 14px 22px')
    expect(css).not.toContain('var(--motion-ease-expressive')
  })
})
